### ISSUE TITLE
Documentation for css styles refers to out-of-date location

### ISSUE THREAD

**Issue by oskarax** [jflamy/owlcms4#1070]
**Describe the bug**
According to the docs you should find a folder called local/styles/video but i havent got any folder inside local called that. Where is it? Im trying to change colors for the streaming.

"The style sheets for the video streaming are actually separate from those used on-site. You can change the color scheme for the videos without affecting the main site. The video style sheets are located in local/styles/video"

**owlcms version**
version 50.0.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jflamy** [comment]
The documentation is out-of-date and will be updated.  Styles are in `local/css`.  You can use any of the directories in there to be the video styles.  Normally people use either `nogrid` or `transparent`.  You would copy this folder to a name you pick (for example, `vid`), and edit.
Then on this page you would pick the style you created


![Image](https://github.com/user-attachments/assets/088862b5-675e-4418-9be4-dbe1415d049d)

**Comment by jflamy** [comment]
Fixed in https://owlcms.jflamy.dev "live" documentation (full name https://jflamy.github.io/owlcms4/#/index)
