### ISSUE TITLE
Syntax error in build instructions

### ISSUE THREAD

**Issue by maglunengineering** [jflamy/owlcms4#1077]
It seems to me that there is a syntax error in the build command written in BUILDING.md, which is

`mvn -P production -am -pl clean owlcms package`

This command fails with the error "Could not find the selected project in the reactor: clean @". 

The 'clean' must be put before the -pl, for instance like this: 
`mvn clean -P production -am -pl owlcms package`

**Comment by jflamy** [comment]
The mvn command syntax from the help message is
`mvn [options] [<goal(s)>] [<phase(s)>]`

The build has two goals, `clean` and `package`.  The project list is `owlcms`. So the correct syntax would be
`mvn -P production -am -pl owlcms clean package`  

The documentation has been fixed and will be in 52.0.0-rc05 and later.
