### ISSUE TITLE
Wrong "next weight" shows for announcer

### ISSUE THREAD

**Issue by Bravissimo594** [jflamy/owlcms4#1107]
**Describe the bug**
At the NAOS2 in Fort Worth, Texas, announcers had the wrong "next weight needed on the bar" initially flash up for the announcer after a lift. It appears that the next weight for the particular lifter who just lifted comes up before sharing the screen with the next weight needed on the platform.

**owlcms version**
Whichever version was used at 2024 NAOS2.

**To Reproduce**
1. Lifter lifts
2. Officials give decision
3. Incorrect "next weight" appears
4. Correct "next weight appears"
5. Incorrect "next weight" disappears

**Expected behavior**
Only the next weight actually needed on the platform should appear.

**Screenshots**
Video of screen progression at [https://photos.app.goo.gl/w6XPcc7Pq4usBpAE8]

**Desktop (please complete the following information):**
 - OS: MS Windows 11
 - Browser: Chrome
 - Version: Latest as of August 29, 2024

**Additional context**
Lots of competitions were running simultaneously, as shown in the screen video linked above. Let me know if I can provide further details. Thanks!
-- Michael Keating --

**Comment by scottgonzalez** [comment]
This was actually fixed before NAOS2 ended :-)

Original bug: https://github.com/jflamy/owlcms4/issues/1084
Fix: https://github.com/jflamy/owlcms4/commit/efc71d7ed26a1670ee1da2c6d966aabb8432f1aa

**Comment by jflamy** [comment]
We did not feel like updating the system mid-course for such a glitch.  The system ran uninterrupted from beginning to end.
