### ISSUE TITLE
Dropdown showing strange text

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#1146]
**Describe the bug**
Some dropdowns (for instance under Results=>Team Results) show strange text for some items in the dropdown

**owlcms version**
version 53.1.1

**To Reproduce**
1. Make sure that a competition named Nordics is present in the system
2. Run a competition
3. Go to Results=> Team results and try to select Nordics

**Expected behavior**

**Screenshots**
Screenshot of the problem attached
![StrangeText](https://github.com/user-attachments/assets/28adc409-10a6-4f78-a9e4-b2a14340493f)

**Comment by jflamy** [comment]
The pre-established championships have translations.  Those that don't should be shown as entered.

**Comment by jflamy** [comment]
(!en:blabla means that there is no translation for the key "blabla" in the language "en").
