### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#1147]
**Describe the bug**
A translation seems to be missing under Results=> Import from an offline site

**owlcms version**
version 53.1.1

**Screenshots**
Screenshot attached
![Missing translation](https://github.com/user-attachments/assets/7d4e9f19-f277-4a7f-acbd-f6e32099aab7)

**Comment by jflamy** [comment]
missing translation for "en".  fixed in next v54 build.
