### ISSUE TITLE
Attempt board not showing collars when loading low weights on 15 kilo bar

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#1149]
**Describe the bug**
When loading low weight (< 40 kilo for female lifters) the Attempt board is not showing the collar

**owlcms version**
version 53.1.1

**To Reproduce**
1. Create a sesssion with one female lifter with a starting weight under 40 kilos
2. Make sure all bumper plates (including 5 and 2.5 kilos) are activated
3. Start session and evaluate the Attempt board

**Expected behavior**
Collars should be included on the graphic

**Screenshots**
Screenshot of Attempt board attached
![Attempt board](https://github.com/user-attachments/assets/9ab279a6-3de2-4949-9203-7490083ab5ea)

**Comment by jflamy** [comment]
That was intentional, as neither USA nor Canada uses collars for low weights.
Now configurable in version 54 on the Plates and Barbell page.  The default for "no collars" is still 40, so you will need to change it.
