### ISSUE TITLE
On 54.0 The score and rank does not show up on the scoreboard

### ISSUE THREAD

**Issue by LynValencia** [jflamy/owlcms4#1171]
**Describe the bug**

**owlcms version**
version 54.0

**To Reproduce**
1. Go to Non standard rules
2. select show overall rank on scoreboards, show score on scoreboard, Medals according to Overall Best Athlete Score 
4. The score and rank are blank on the scoreboard 

**Expected behavior**
The score and the rank should be shown on the scoreboard 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] Chrome
![Screenshot 2024-12-11 215253](https://github.com/user-attachments/assets/dcbad675-ed5d-48f2-9da4-943a20f78646)
![Screenshot 2024-12-11 215155](https://github.com/user-attachments/assets/ad373143-f69c-42d8-9862-7dda4eb88edf)

**Additional context**

**Comment by jflamy** [comment]
Will provide alternative

**Comment by jflamy** [comment]
Just uncovered an issue, the scoring system option is not visible in 54.0.0 (was hidden by mistake).  Am fixing that and will release asap.

**Comment by jflamy** [comment]
In 54.1.0-rc01 there is now SM and SF in the default age groups file, and the editor has been fixed.

![Image](https://github.com/user-attachments/assets/63b1f78e-731b-46bc-ad8a-ac437a770963)
