### ISSUE TITLE
Force next lifter

### ISSUE THREAD

**Issue by marttimato** [jflamy/owlcms4#125]
It is not possible to force the next lifter, ie change the lifting order.

**Comment by jflamy** [comment]
True.  I am curious though.  In what circumstanances have you  used this ?
I don't recall it being used in any meet I've seen in the past few years,
so the feature just slipped out of my head.

**Comment by marttimato** [comment]
When there are only few lifters in a club meet, we go through the lifts in a round-style way, everyone lifts their first lift and then everyone lifts their second lift ... That´s the situation when we used 'force next lifter' button.

**Comment by jflamy** [comment]
Fair enough, will look at adding it back (I don’t believe I removed the code from the athlete sorting routine).  Given that there are no longer any buttons in the grid, the button will most likely be on the athlete card.)

Jean-François Lamy

De : marttimato
Envoyé le :6 août 2019 08:37
À : jflamy/owlcms4
Cc : Jean-François Lamy; Comment
Objet :Re: [jflamy/owlcms4] Force next lifter - not possible (#125)

When there are only few lifters in a club meet, we go through the lifts in a round-style way, everyone lifts their first lift and then everyone lifts their second lift ... That´s the situation when we used 'force next lifter' button.

**Comment by jflamy** [comment]
Added back as a checkbox on the athlete card.  The athlete is forced as current until either the checkbox is removed, or the next decision is shown (whether 3 refs or entered by the announcer)

![021_ForcedAsCurrent-](https://user-images.githubusercontent.com/678663/62574332-3eb90a80-b866-11e9-874f-db9b0ce091df.png)
