### ISSUE TITLE
Age Group assignment

### ISSUE THREAD

**Issue by ditorelo** [jflamy/owlcms4#141]
Hello!

I'm adding an athlete born in 1985 and they are getting assigned to the M21 group automatically. I can't change that and I can't find where to manage the age groups.

<img width="939" alt="Screen Shot 2019-08-22 at 1 30 15 PM" src="https://user-images.githubusercontent.com/642102/63479160-22ad9e00-c4e1-11e9-8653-91843beeb65d.png">

Am I missing something?

**Comment by jflamy** [comment]
Please provide a full screen shot.  That column would be the body weight category.  And the program does not provide a M21 body weight category by default.  Also provide a screen shot of the athlete entry form (the screen where you edit the athlete).

I suspect someone has edited the categories and added a bogus Men 21kg and under -- the categories are from the database, and edited in the Preparation/Define Categories screen.


Age divisions are currently predefined and not edited -- (they are DEFAULT, SENIOR, JUNIOR, YOUTH, KIDS, MASTERS, A, B, C, D ) -- but what is shown there is not an age division.

**Comment by ditorelo** [comment]
Can't reproduce anymore, will report in case come across it again.
