### ISSUE TITLE
Multiple groups on screen at once

### ISSUE THREAD

**Issue by ditorelo** [jflamy/owlcms4#146]
Is there anyway we can display multiple groups on the various screens for smaller competitions as per screenshot attached (groups in this case are WOMEN, MEN)?

![68568203_3506084522750330_5163419188013826048_o](https://user-images.githubusercontent.com/642102/63734144-3e44ea00-c8cf-11e9-8766-503d09bade1c.png)

**Comment by jflamy** [comment]
You can have several categories per group all together.  We do this all
the time for youth competitions where everyone is using the same bar weight
-- you can create a group G1 (say) and assign yf40 yf45 and m49  together
as a single group.  In such a case, we use the technical controller screen
and tell it to force the bar weight to 15kg (or 10kg for kids)

It is hard to see how you would have men and women on the same platform
given the different bar weights.  But if you do switch bars he program
doesn't care and will compute the plates loading correctly.

If you look at the demo, the program actually shows two categories on the
same screen.  You can use the age divisions also.  You could have
youth female 45, junior female 45 and senior female 45 together with male
youth 49 in a single group.  The scoreboard would show the 4 different
sections in the official IWF display order (age groups ascending, women
before men, lighter categories before heavier ones).

If you have two platforms, each platform has its own scoreboard, there is
not currently a combined scoreboard.


[image: image.png]



Le lun. 26 août 2019 à 21:34, Diogo Freire <notifications@github.com> a
écrit :

**Comment by jflamy** [comment]
The only difference with the display and the request is the order of the categories on the screen.
Program currently uses IWF ordering, which would show youth before juniors before seniors before masters, and women before men in each division.  The program does not use headers between each category to save screen space (many competitions have 20 lifters per group)
