### ISSUE TITLE
Athlete Image on Scoreboard

### ISSUE THREAD

**Issue by coach-austinbarbell** [jflamy/owlcms4#205]
Would like to request a feature enhancement  of adding a picture of an athlete to the score board or lifting display. This image (.png .jpg) could be a country/state flag or picture.

**Comment by jflamy** [comment]
I replied to this in another message, sorry.

Noted. However, be aware that this opens a (large) can of worms regarding
personal information (GDPR in the UK, CCPA in California) as this is
considered personal information that is not inherently required for the
purpose of the program (whereas body weight and year of birth are
inherently required).   There is also the fun stuff of where to put it --
In Québec we have a generation of athletes with names like Jean-Christophe
Duvernay-Tardif  and some countries use "West-End Crossfit and Weightlfting
Club" as team names (look at pictures from the Russian championships for
fun).  I have redone the attempt board with those long names in mind, not
so sure where to put the picture.  Perhaps on top, too bad for the very
long names.

**Comment by jflamy** [comment]
Having redone the attempt board, I have ideas on how to handle this.
Will be tracked as part of request #508
