### ISSUE TITLE
Language Selection on Athletes Cards

### ISSUE THREAD

**Issue by coach-austinbarbell** [jflamy/owlcms4#237]
**OWLCMS:** Version: 4.2.2 + 
**Platfrom:** Win10 & Mac 
**Browser:** Safari, Chrome

When Exporting athlete cards there are some French elements that still persist without translation when language is switch to English.

**Identified Fields:**

"Progression automatique"
"Poids déclare"

[cards_all-5.xls.zip](https://github.com/jflamy/owlcms4/files/3841604/cards_all-5.xls.zip)

**Comment by jflamy** [comment]
Fixed (will be in next release).  Meanwhile you can edit in your local/i18/templates/cards/CardTemplate_en.xls and replace with "Automatic Progression" and "Declaration".
