### ISSUE TITLE
Indicate that a weight change is requested by the current athlete on the attempt board

### ISSUE THREAD

**Issue by alupa15** [jflamy/owlcms4#264]
[Translating the request]
It is requested to indicate "Change" on the attempt board instead of the remaining time when the weight is being changed by the marshall
[end translation]

Marquer "Changement" ou "change" sur l'écran essais en cours à la place du temps lorsque le Mashall change le poids ou coupe le chrono pour le changement de barre.
Deuxième question, souhaitez vous les documents francais pour les juges et pour les cartes ahtlètes?

**Comment by jflamy** [comment]
Answering the question first  -- svp faire des items séparés, c'est plus facile.

All documents are already translated in French and are automatically selected as such if the locale is fr .  -- tous les documents sont déja traduits en français, si vous choisissez la locale dans la page "Jnformation sur la compétion" ou bien que vous mettez la variable d'environnement OWLCMS_LOCALE=fr . Dans les deux cas, cette information est lue au démarrage.

**Comment by jflamy** [comment]
Not sure about this.  It is important for the jury and referees to see how much time is left on the clock to see if the request is legal.  I would be more inclined to hide or change the kg indication.

Pas certain. Je crois qu'il faut garder le temps pour que les officiels et le jury voient combien il en reste et si la demande est recevable.   Je serais plutôt enclin à retirer ou changer les kg affichés.

**Comment by alupa15** [comment]
ok oui c'est pas faux, je pense que cette façon la est mieux.

**Comment by jflamy** [comment]
Actually, there is no longer a "weight change" button on the announcer and marshall screen because no-one was using it.  They would simply stop the time.  Not clear that if the marshall stops time the only reason is for the current athlete.  The natural thing is to click on the changing athlete and do the weight change, after looking at the time left.
So other than showing a notification on the screen there is no way to know why the time was stopped.
I will put that on the back burner.

**Comment by alupa15** [comment]
Bonsoir,
Ok je comprends vos arguments. Et si le mot "change" apparaissait lors du clique sur l'athlète ou quand on valide le changement. C'est peut-être une autre solution.
Bonne journée

**Comment by jflamy** [comment]
La déclaration (avec ou sans changement) par l'athlète courant est signalée
aux autres officiels comme l'annonceur et le préposé (marshall); c'est une
voie plus facile; je crois que l'intérêt est surtout pour les arbitres et
le jury.
