### ISSUE TITLE
🐛 [Duplicate #254] Result package is empty 

### ISSUE THREAD

**Issue by marcianoskate** [jflamy/owlcms4#265]
After completing our competition, the Results Package excel file is always empty. 

Attached are the logs and db:
[debug.zip](https://github.com/jflamy/owlcms4/files/4028384/debug.zip)

**Comment by jflamy** [comment]
Please do not send logs and db to the whole list; send them to me directly
or even better create an issue on github.

Le lun. 6 janv. 2020 à 19:30, marcianoskate <notifications@github.com> a
écrit :

**Comment by jflamy** [comment]
As indicated in my direct reply, the problem shown in the logs has been
fixed in version 4.2.11.
(https://github.com/jflamy/owlcms4/issues/254)

**Comment by jflamy** [comment]
Deepest apologies.  The mails coming from github and the forum end up in the same mailbox and look very much the same.  I thought you had sent the logs to the whole list.  Thank you very much for opening the issue.
