### ISSUE TITLE
Athlete Start Cards - Alignment

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#278]
It seems that the new athlete cards are formatted a bit differently, and therefore you can't fold the sheet directly in half and cut them, or tear them.

It might be a cosmetic thing, but it takes a bit more time for me to separate them, because they are no longer the same size, so i cut them to be the same size.

Is it possible to adjust the excel file for future releases?

**Comment by jflamy** [comment]
As a quick workaround, select "center vertically" in the margins tab of the page setup dialog.

![image](https://user-images.githubusercontent.com/678663/72473794-7339d680-37b5-11ea-8328-f03364ed128b.png)

**Comment by jflamy** [comment]
Please find enclosed corrected templates for US Letter paper.
Unzip and drop the files in the local/templates/cards directory where the program is installed.

[cards.zip](https://github.com/jflamy/owlcms4/files/4068847/cards.zip)

**Comment by jflamy** [comment]
Fixed in 4.3.2.2 now on github.
