### ISSUE TITLE
Make it possible to Unsort Announcer List

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#279]
If the announcer decides to sort the list of athletes on the page, for whatever reason, there is no way change the display back to unsorted/automatic sorting unless you close the page and reload,

Closing and reopening is fine, but some users may not think of this

**Comment by jflamy** [comment]
You could hit the Refresh button.  I could add the lifting order column with the rank, that would perhaps be more natural.

**Comment by jflamy** [comment]
To clarify : the refresh icon just above the grid will reload in the proper sorting order.

**Comment by jflamy** [comment]
The framework was keeping the previous sort order even when reloading the grid records.  Had to read the source to find the somewhat counterintuitive way to reset the sort order (which is to invoke the sort method with a null sort order).
