### ISSUE TITLE
[Feature Request] Lockout period for accidental "Good/Bad" lifts

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#281]
I suggest a couple second lockout period for the good/bad lift button. This can prevent accidental double clicks and accidental "lifts"

**Comment by jarble7** [comment]
We also had a situation in a competition where the Announcer was clicking good lift even though the judges were saying good lift through their devices. This led to an erratic behaviour that the competition people couldn't figure out right away.

No one would lift 2 weights on the platform within 3 seconds of each other, for example.

The lockout function could be an option you choose as well.

**Comment by jflamy** [comment]
Debounced buttons. 1000ms delay required between two successive clicks.

**Comment by jarble7** [comment]
This was for the web interface, right? The referee buttons have no issue with this. 

Brock Pedersen

**Comment by jflamy** [comment]
However doing green followed by red within 3 seconds doesn't do a reversal. Will need to check that.

**Comment by jflamy** [comment]
Fixed.  Single referee can now click good then reverse within 3 seconds for dropped bar, foot on bar, or suchlike.

**Comment by jflamy** [comment]
Yes, on the announcer page, when refereeing solo or when using 
flags/cards/thumbs.
Or when a ref goes MIA on a virtual meet.



------ Original Message ------
From: "jarble7" ***@***.***>
To: "jflamy/owlcms4" ***@***.***>
Cc: "Jean-François Lamy" ***@***.***>; "State change" 
***@***.***>
Sent: 2021-04-11 4:50:22 PM
Subject: Re: [jflamy/owlcms4] [Feature Request] Lockout period for 
accidental "Good/Bad" lifts (#281)

>
>This was for the web interface, right? The referee buttons have no 
>issue with this.
>
>Brock Pedersen
>
>Sent from my phone
>
