### ISSUE TITLE
Timer oddities when using tabs

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#282]
I had started the break timer, and went to a screen that showed the results, it was displaying 10 minutes, I then went to a different display and the timer showed 9 minutes. Then I went to the break timer box and it showed another different time.

See the video https://share.icloud.com/photos/0A7PaotV4CiZgJo5W2OjnDvxA#Port_Coquitlam_-_Riverwood

**Comment by jflamy** [comment]
Ah!  Not a true bug (programmer answer).  When the tab is not at the front, JavaScript stops sending the frame updates; the timer countdown is latched to the frame updates.    I made an attempt at getting an event when the tab gets focus to recompute the time elapsed and "catch up" with the lost time, but I never got the events and I lost patience.  

This does not happen if you have independent windows with the timer at the front.  This is actually documented cryptically when running on the cloud and the announcer needs to produce the sound via the browser -- see the very bottom of [this page](https://jflamy.github.io/owlcms4/#/Preparation?id=associating-an-audio-output-with-a-platform)

**Comment by AndersBIK99** [comment]
I am writing here as I think to issue I noticed is related. The lifting order screen consequently fails to update correctly when a break finishes. During the competition we had to F5 the screen after each break (the screen simply went black with only the header showing). It could also be related to switching groups as we after each group immediately switched to the next group and then started a break.

Also we noticed that if the speaker during the break switched to a different screen then the break timer window disappeared. When we pressed the break button the window reappeared but the timer was not in sync with the break. This caused some confusion with the speaker trying to start the break again by pressing the start button until I told the speakers to just look at the scoreboard where the break timer worked fine.

**Comment by jflamy** [comment]
Something peculiar is going on.  The athlete timer is able to call back to the server to resync when brought back to the front.  The break timer (exact same code) is not.  I suspect that this has to do with which one is created first.

**Comment by jflamy** [comment]
Appears to be fixed in 4.5.0-beta2, except for the one case where the tab did not react to the XHR push from the server.  In that second case, just clicking on the screen usually wakes things up, but the javascript timer starts at that time, and is late.   A Refresh fixes things up (now that timer refreshes are consistent across all running windows).
