### ISSUE TITLE
[Bug] Athlete assigned to category but not really

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#283]
I had assigned all the lifters to their masters category, and 1 lifter in particular was not showing as changed, eventually I went to the Athlete Registrations page and it showed her as not in the masters class, but I had changed her category through the weigh in screen. After updating her in the Athlete Reg screen it worked,

**Comment by jflamy** [comment]
Can you point out the athlete? (can be via mail, offline)
