### ISSUE TITLE
Introduce an option to lock result fields in the marshall screen

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#286]
We had an issue where the marshall accidentially deleted a result when trying to increase a lifter. As it is rare that the marshall needs to change the actual weight lifted I suggest that the result fields are left read-only in the marshall screen. 

In the event that changes needs to be made (that happens too) then there could be an option button of some kind to open up the fields for editing. The default should be locked in my oppinion.

**Comment by jflamy** [comment]
Undesirable scenario as follows

1. Marshall updates request, leaves card open
2. Athlete lifts.  This updates the result in the database
3. Marshall updates.  This wipes the result on the database. 

Implementing version check is hardly justified. Likely easier to prevent update of results unless the marshall or announcer explicitly unlocked the results row.

**Comment by jflamy** [comment]
- Marshall can no longer edit by default; checkbox is required
- Marshall does not sent results updates unless checkbox allowing editing is on.
