### ISSUE TITLE
Timingstats are wrong

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#288]
It seems that timings stats are not calculated correctly. I have attanched a database plus the generated statistics. The competition started at 10 AM and finished at 7 PM - around 9 hours of weightlifting.
[DBandTimingstats.zip](https://github.com/jflamy/owlcms4/files/4082881/DBandTimingstats.zip)

**Comment by jflamy** [comment]
If you hit "enable editing" on the file, the statistics are computed .  Hmm. The computation of the start times could be wrong.
![xMlqKaPD0r](https://user-images.githubusercontent.com/678663/73584536-169e1300-4467-11ea-8904-62fcdecb575e.png)

**Comment by jflamy** [comment]
The time of lift was not only recorded at the actual time of a lift, but also other editing changes could affect the time recorded (something my test cases did not catch).  Should be Fixed in 4.4.2.

**Comment by AndersBIK99** [comment]
That could definitely explain the weird stats.

Thanks!

Den lør. 1. feb. 2020 kl. 15.31 skrev Jean-François Lamy <
notifications@github.com>:
