### ISSUE TITLE
Upload of excel template says succesfull but no data is saved to the database

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#32]
Dispite a message saying upload succesfull no data seems to be saved. Version 4.0.12
The template file is attached
[registration_test.zip](https://github.com/jflamy/owlcms4/files/3126983/registration_test.zip)

**Comment by jflamy** [comment]
Fixed insertion of athletes (missing call to EntityManager.flush()) -- I swear this used to work ;-)
Tiny bit of work still needed to tell program that the competition just read from Excel is the correct entry (copy properties to override)

**Comment by jflamy** [comment]
Fixed competition data update as well.
