### ISSUE TITLE
spurious validation: allow non standard bar to be 0 when not checked

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#324]
When you adjust the plates, even if non-standard bar is not checked it cannot be 0

**Comment by jflamy** [comment]
I do not understand.  You can't lift without a bar, and the system does signal the error.

![image](https://user-images.githubusercontent.com/678663/76165239-c6803380-612b-11ea-8b21-71b36e0be3b7.png)

**Comment by jarble7** [comment]
I added the weight of 2.5kg to the bumper plates, and did not edit the Bar weight to be anything else. It gave the error as you pictured. The option was not checked.

**Comment by jarble7** [comment]
![Annotation 2020-03-08 113855](https://user-images.githubusercontent.com/45324279/76168976-6e4c3000-6131-11ea-9355-63dfeaf52695.png)

**Comment by jarble7** [comment]
See above, I do not have Non-Standard Bar checked

**Comment by jflamy** [comment]
Ok, now I get it.
