### ISSUE TITLE
Master W70+

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#325]
I believe the Women’s 70+ age group is not actually 70+ in the Masters setting. 

I have since changed my database and forget exactly what it’s setup as. But there was something wrong with the 70+ group.

**Comment by jflamy** [comment]
70+ is correct as per IWF Masters rules (70 and over)
Canada has 70-74 and 75-80 and 80+ same as men.
So there is a 70 (70-74) and a 70+ (70-999)

The bodyweight categories were wrong, however (spurious 40kg category for several Women's groups, now fixed.)

**Comment by jarble7** [comment]
I think that was the issue i saw. There is F70 and F70+ and F75 and F80. I was confused.

I guess I don't have to enable them all

**Comment by jflamy** [comment]
My understanding was that for Canada men and women were now identical, with M30 added.  I cannot find reference on Canadian Masters federation site.

**Comment by jflamy** [comment]
For Canada, the competition groups are M30 to M80+ for both sexes.  However, records are awarded for M80, M85, M90... in five-year slices (confirmed by masters prez).
