### ISSUE TITLE
Timekeeper on tablet or phone

### ISSUE THREAD

**Issue by AJAYDAS75** [jflamy/owlcms4#340]
One more request regarding time keeper control panel if it can be made bigger icon to operate from tablet or I Pad than it will be very comfortable and user friendly.Thank you.

**Comment by jflamy** [comment]
![050_Timekeeper](https://user-images.githubusercontent.com/678663/79700100-7be0f380-8261-11ea-8c87-81d19e5d1165.png)

**Comment by jflamy** [comment]
Also added "," and "." as shortcuts for starting stopping clock from a programmable keypad when using a laptop.

**Comment by jflamy** [comment]
Sizing wrong when using Chrome on Android phone.  Works when desktop version is used explicitly. Investigating.

**Comment by AJAYDAS75** [comment]
Awesome Brother,thank you so much.
