### ISSUE TITLE
Scoreboard Multiple Ranking Feature

### ISSUE THREAD

**Issue by geohussain** [jflamy/owlcms4#372]
I have noticed from the screenshots of the scoreboard that it does not feature showing the rank of the athlete for different age categories.

So, it is hard to differentiate which rank the scoreboard refers to if the athlete is registered in multiple age categories.

Is it possible to show multiple ranks in the scoreboard if the athlete is registered in multiple age categories?

**Comment by jflamy** [comment]
The athlete belongs to an age category, which is shown on the board, and for which the rank is computed.
This category is by default the more specific category -- an 18-year old would be a Junior by default in a competition with both Jr and Sr.

I don't see how to show this cleanly on the boards, and I don't think I have ever seen an example of such a display. If you have good examples, kindly share.

**Comment by geohussain** [comment]
In the middle east competitions, we have young players playing in multiple age groups because they are young.
Hence, we use the attached scoreboard from the Excel Sheet.

![weight_lifting](https://user-images.githubusercontent.com/6234238/89125184-41842500-d4e5-11ea-9b48-6176bfd1c9d8.png)

**Comment by jflamy** [comment]
Thanks.  I will have to think about this.  When I asked the main users of the program, most federations either ran "one age group at a time" -- this is the senior championship, so all athletes compete as seniors, or ran "age-group championships", so athletes had to pick which age group they were in (senior or masters, for example).

So the program currently does not maintain multiple ranks for a single athlete.

**Comment by geohussain** [comment]
The middle eastern weight lifting committee requires that any application or spreadsheet used in their competitions to have this feature in its scoreboard (multiple rankings for multiple age groups).

**Comment by jflamy** [comment]
Noted.

**Comment by jflamy-dev** [comment]
Added a scoreboard "multiple ranks".  Also updated the final package. If needed for a single group, the final package can be done for a specific group.

**Comment by jflamy-dev** [comment]
Will be available as of 4.13.0.  See pre-releases at https://github.com/jflamy-dev/owlcms4-prerelease/releases

**Comment by geohussain** [comment]
Thank you so much.
I will test it out soon.
