### ISSUE TITLE
Enhancement to registration template

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#374]
I suggest enhancing the Excel-template in order to be able to fully prepare a competition off-line.

As it is now groups, start time, weigh-in, assigned referees etc has to be created in the system before loading data from the template (if you want lifters to end up in the correct groups). 

On many occasions the basic preparation could easily be done up front which could often help simplify thing on "game day".

**Comment by jflamy-dev** [comment]
Actually, only the groups need to exist beforehand.  But a more sophisticated spreadsheet would be useful, agreed.

**Comment by jflamy-dev** [comment]
Enhancement: the registration spreadsheet template now contains a second tab to define the groups (name, platform, times, technical officials) (#374).  Also, the athletes, groups and platforms are reset/updated on upload so that the spreadsheet is a now a better tool to crosscheck entries

**Comment by AndersBIK99** [comment]
Excellent!

I'll give a try in the very near future as we have a competition coming up
at our club shortly.

Den ons. 12. aug. 2020 kl. 05.28 skrev jflamy-dev <notifications@github.com

**Comment by jflamy-dev** [comment]
Available in 4.9.2-alpha05
https://github.com/jflamy-dev/owlcms4-prerelease/releases
