### ISSUE TITLE
technical controller screen not loading in Spanish

### ISSUE THREAD

**Issue by martin715burela** [jflamy/owlcms4#381]
Hello,

First of all, congratulations. Your work here is awesome!

I've checked the software and it works really well but I have a question about the load chart because I've installed the last version and it isn't displayed. I don't understand why but I can display the chart on the attempt board as wiki:

![imagen](https://user-images.githubusercontent.com/69551989/89960367-27fa8000-dc3f-11ea-862f-b3a6b56f4358.png)

Could you check this issue? And Thanks a lot for your dedication. Regards.

**Comment by jflamy** [comment]
The load chart is accessible on the Technical Controller screen

![msedge_ZWdZHanwmO](https://user-images.githubusercontent.com/678663/90019647-b6412700-dc7c-11ea-9904-06ae8f62a20c.png)

You can have multiple tabs open at the same time, so you can switch easily.

![tAvmCliZ4T](https://user-images.githubusercontent.com/678663/90019800-e8528900-dc7c-11ea-8862-3739d766321a.png)

**Comment by martin715burela** [comment]
Thanks!

I've checked it again and the issue is when I choose Spanish as language. In this case, occurs an exception: _"There was an exception while trying to navigate to 'lifting/tc' with the exception message 'Unable to create an instance of 'app.owlcms.ui.lifting.TCContent'. The constructor threw an exception.'

So, I can't use the tab of Technical Controller.

Regards,

**Comment by jflamy** [comment]
I will check.   The translations use special sentences with slots and 
rules when the formatting or word ordering is different between 
languages.  Sometimes the translators break these strings in the process 
of translating.

------ Original Message ------

**Comment by jflamy** [comment]
Will be fixed in next pre-release.  Please check https://github.com/jflamy-dev/owlcms4-prerelease/releases for a release 4.9.0-alpha04 or more recent later today.
![image](https://user-images.githubusercontent.com/678663/90026887-eb05ac00-dc85-11ea-989f-f4cef471951b.png)

**Comment by jflamy-dev** [comment]
Fixed in 4.9.2-alpha05
https://github.com/jflamy-dev/owlcms4-prerelease/releases
