### ISSUE TITLE
Problème avec télécommandes Delcoms

### ISSUE THREAD

**Issue by alupa15** [jflamy/owlcms4#384]
Bonjour,
J'ai commandé les télécommandes Delcoms pour réaliser les compétitions. Petit problème, je les ai configurés. Lors de l'utilisation en jury, elles fonctionnent, les décisions s'affichent. Lorsque je les utilise en tant qu'arbitre de plateau, cela ne fonctionne pas. J'utilise Firefox pour le logiciel. Lorsque j’appuie sur le bouton bleu, rien ne se fait, quand j'appuie sur le bouton rouge, la barre recherche rapide s'affiche et apres des "é" - "-" apparaissent quand je rappuie sur les rouges ou "&" ou " s'affichent.
Que dois-je faire?

**Comment by jflamy** [comment]
Probablement un problème de choix de clavier différent sur les deux postes.  Les claviers configurés pour la France demandent la clé Maj. pour taper les chiffres, contrairement à la majorité des autres pays occidentaux.

Sur le poste utilisé pour l'arbitrage, ouvrir un éditeur de texte.  Lancer Notepad (si sur Windows, ou un éditeur de texte sur Linux). Brancher la manette et cliquer dans Notepad.  On doit voir les chiffres 1-2 3-4 5-6 (selon la manette).

Il faut que les manettes arbitre soient configurées en fonction du clavier du poste arbitre.  Le plus simple est probablement de mettre le clavier du poste arbitre en mode "Anglais-US" car c'est ce qui correspond au logiciel de programmation de la manette.  Sinon, j'essaierais de programmer la manette pour rajouter "LShift" (Left Shift, la clé Maj. de gauche).

**Comment by alupa15** [comment]
Merci pour votre réponse, Cela fonctionne correctement.

**Comment by jflamy-dev** [comment]
Curiosité - j'aimerais en savoir plus sur votre club/fédération etc.  Un mail à jf@jflamy.dev pour faire connaissance ?
