### ISSUE TITLE
(Heroku) Excessive scoreboard delay updating top part.

### ISSUE THREAD

**Issue by jflamy-dev** [jflamy/owlcms4#399]
Happens on Heroku, on very large competitions (30 groups)

- Could be garbage collection with large number of lifters - check JDK settings.
- Could be needless recalculations.

**Comment by jflamy** [comment]
Java behaviour visibile on memory-constrained configs (such as free tier of Heroku): lack of memory prevents threads from being created.  
Fixed by proper memory allocation: see https://owlcms.github.io/owlcms4/#/HerokuLarge
