### ISSUE TITLE
ORDER OF CALL WHILE RUNNING COMBINED AGE GROUPS

### ISSUE THREAD

**Issue by AJAYDAS75** [jflamy/owlcms4#401]
Sir it is good to have a features for running the competition for all the ages combinedly. But there is an issue in order of call while  running all the age groups combined.

**Comment by jflamy-dev** [comment]
Please provide a specific example. 

Age is not used in the calculation of the lifting order, except as part of the start number.  If two athletes request the same weight on their first try, the lowest start number is used.  In Masters competitions, the older age groups go first, by tradition, and get a higher start number.  In age group competitions that involve multiple age groups, it is customary for younger athletes to go first, and to give them lower start numbers.  But this only affects the first lift, and is known in advance as soon as the starting weights are made visible, so I fail to see how it can be much of an issue.

**Comment by AJAYDAS75** [comment]
Sir I will try to send pic or video

**Comment by jflamy** [comment]
No other information was received, no other report.  Will reopen if more information becomes available.
