### ISSUE TITLE
Allow selection of scoreboard contents

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#465]
Allow selection of which columns and which sections are shown.
Create a menu to pick configs
Create pre-defined configs
Investigate storing custom configs

**Comment by JDFS404** [comment]
For public results, I would suggest this as well (if not already for this app). In this way I can proxy ```scorebord1.subdomain.nl``` to one TV with an Amazon Fire Stick and ```scorebord2.subdomain.nl``` to another TV with another Amazon Fire Stick.

**Comment by jflamy** [comment]
Display parameters are currently implemented as query parameters. Curious as to why you would have two different scoreboards for the public given that the system only runs one meet at a time.  One cluster is one competition container, one database,  one public results.

**Comment by jflamy** [comment]
If there are multiple platforms in one meet there is already a choice and a query parameter in the url

**Comment by JDFS404** [comment]
Sorry, maybe I'm getting it wrong; we would like 1 screen for the public and 1 for the warm-up area, but perhaps that's already possible?

**Comment by jflamy** [comment]
You can have as many displays as you want. Each browser is an independent session. All competition site displays connect to the same backend.  Each display is Independant in terms of size, colour scheme etc.

**Comment by step22rus** [comment]
The scoreboard can still switch to the awarding of the group! This is set in the scoreboard settings. Thus, the public scoreboard can show 1,2,3 places, and the warm-up scoreboard will not switch to awarding. This is convenient when the awards are held during the break before snatch.

**Comment by jflamy** [comment]
Manual hiding/unhiding of columns can be done in 4.33.0 using the CSS file.  Not sure yet what to do about the user interface.  Probably in the competition rules.

**Comment by jflamy** [comment]
No current plan to go beyond what is available in 4.33.1 using the CSS file.
