### ISSUE TITLE
Can't load registration data Excel

### ISSUE THREAD

**Issue by danirueda** [jflamy/owlcms4#472]
Since a few versions. I don't remember what (4.27 or 4.26), I can't load registration Excel. I select file but nothing happens. I open browser console but there aren't any errors. This is my browser capture showing console messages after selecting my registration sheet.

![image](https://user-images.githubusercontent.com/16139263/154767281-5498f1b9-a05e-466d-8ee8-14d822a4570d.png)

I read #338 and I thaught this would resolve this in v4.29.0 but I was wrong.

I start always from scratch. So, no database model conversion is needed from older versions.

### Technical info
* OWLCMS version: v4.29.0
* Tested browsers: Google Chrome, Brave and Firefox.
* Operative system: Ubuntu 20.04.3 LTS

**Comment by jflamy** [comment]
Please drag and drop your excel in a comment to this issue so I can look at it.

**Comment by danirueda** [comment]
This is my server log output since starting until I drop Excel registrarion.
```
13:03:01.880 INFO  starting web server                                                         [app.owlcms.Main:94 run]
13:03:02.115 INFO  Database: jdbc:h2:file:/home/dani/Documentos/Halterofilia/owlcms-4.29/database/owlcms-h2v2;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=4, inMemory=false, schema=update [app.owlcms.Main:329 h2FileProperties]
13:03:09.543 INFO  started on port 8080                                                        [app.owlcms.Main:131 run]
13:03:09.550 INFO  using per-session browser language                                          [app.owlcms.Main:249 overrideDisplayLanguage]
13:03:09.677 INFO  local override directory = /home/dani/Documentos/Halterofilia/owlcms-4.29/local [app.owlcms.utils.ResourceWalker:61 checkForLocalOverrideDirectory]
13:03:10.030 INFO  database not empty: Competition ?                                           [app.owlcms.Main:189 injectData]
13:03:10.230 INFO  FOP A    Pushing results to remote site not enabled.                        [app.owlcms.uievents.EventForwarder:123 <init>]
13:03:10.235 DEBUG FOP A    setting clock owner to null [(FieldOfPlay.java:764)]               [app.owlcms.fieldofplay.FieldOfPlay:1508 setClockOwner]
13:03:10.236 INFO  FOP A    entering INACTIVE (OwlcmsFactory.java:119)                         [app.owlcms.fieldofplay.FieldOfPlay:1067 setState]
13:03:10.238 INFO  initialization done, allowing requests.                                     [app.owlcms.Main:137 run]
13:03:10.713 WARN  Cannot start browser: The BROWSE action is not supported on the current platform! [app.owlcms.utils.StartupUtils:194 startBrowser]
```

And this is my [registrarion Excel](https://drive.google.com/file/d/1gNhgSfU2_-E55NiAt3tM-eJjYGY8LhUl/view?usp=sharing). Github does not let upload Excel files to issues. So I attach Google Drive file link.

> You would not see errors in the browser, because the processing is taking place inside the owlcms program that runs on your workstation and send information to your browser (owlcms is a web server).

I can not see errors in browser console but if there is an error in server in AJAX call uploading Excel file, the console would show it up.

This is my console output and, acording to server log I can not see any errors (only a WARN in server).
![image](https://user-images.githubusercontent.com/16139263/154843722-b5e17a34-9872-4699-b5fa-43f934f39059.png)

That is strange. There is a competition soon. If I not find where is the bug, I will have to enter data manually. :worried: 

Thank you!

**Comment by danirueda** [comment]
I forgot to say also I downloaded empty Excel, uploaded it and It still does not work.

**Comment by jflamy** [comment]
I suspect you are on a Mac?  Your file works both on Windows and in the cloud (which is Linux).
A few versions back I added a verification for these two file types on upload (so that when uploading only Excel files would be shown, and have not found information on a different file format being sent from a Mac.
```
application/vnd.ms-excel
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```
Send me your personal e-mail address at jf@jflamy.dev and I will provide you with a workaround

**Comment by jflamy** [comment]
Also, you should put the category bodyweight of the athlete in the registration file.
If the athlete is registered to compete in the 67 kg category, put 67.  The system will put the athlete in the right category (even if there are several categories at the same time)
For heavyweight athletes (109+) put 110 (any weight in the target category will do).

This is unrelated to the problem you are having, but if you fill these numbers I will be able to provide you with a workaround.

**Comment by danirueda** [comment]
No, I'm on Linux.
```
~$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```
For edit Excel files I use [WPS](https://www.wps.com/es-MX/office/linux/). But an empty file registration without editing does not work. With same OS and features I didn't have any problem in past versions.

About body weights. One week before the meeting I load all data execpt body weights. Because there aren't given until weight-in the meeting day. That day I put them manually.

**Comment by jflamy** [comment]
I will check running on Ubuntu. Your browser is running on Ubuntu as well ?

**Comment by danirueda** [comment]
Yes it is. Normally I use Brave. But for this issue I checked also with Google Chrome and Firefox. And the problem is the same. Nevertheless, my SO is Ubuntu with KDE desktop environment. But I think that hasn't probabilities to be related with this issue.

I'm gonna use an older version for the competition next weekend (v4.27 I think). Because today I need to load all athletes to be ready and get an initial backup for doing some tests this week.

If you find something please reply me here. If you wan't, I'll write an email to <a href="mailto:jf@jflamy.dev">jf@jflamy.dev</a> giving feedback about results and doubts in my run competitions. Issues I think is better to write here because maybe they will be useful for some people. :smiley:

**Comment by jflamy** [comment]
Just tried on Ubuntu20.04 with Firefox and it worked.  So I can't say what is going on. Yet.
![image](https://user-images.githubusercontent.com/678663/154859174-ca094ed4-631e-4899-96d8-c1deec4160cf.png)

Please send me your e-mail I will load your data and send you a database snapshot you can load locally.

**Comment by jflamy** [comment]
One more test you can do: if you use the "upload file" button, the file chooser should show you the two types of Excel files accepted (old .xls and new .xlsx).  It should allow you to see the files.   Firefox showed me the empty file correctly.

**Comment by danirueda** [comment]
> One more test you can do: if you use the "upload file" button, the file chooser should show you the two types of Excel files accepted (old .xls and new .xlsx). It should allow you to see the files. Firefox showed me the empty file correctly.

Yes that's correct.

> Please send me your e-mail I will load your data and send you a database snapshot you can load locally.

Sorry, but I don't want to send my registrarion data because It contains personal data from athletes. I hope you understand it.

## Some relevant information
I tested older versions and I found a fact. **v4.26.0** is the latest version which I can load Excel registration. v4.27.0 doesn't work. And It's the same file I linked before.

I will use this for the next cometition.

Thank you!

**Comment by danirueda** [comment]
Hope we can find where the problem is for next versions. :smile:

**Comment by jflamy** [comment]
Please try https://github.com/owlcms/owlcms4-prerelease/releases/tag/4.30.0-alpha00 
I have disabled the user interface filter for accepted file types.   Same as 4.29.0 except for an additional scoreboard.

The reason that there are no errors in the logs is that the file is apparently not sent at all.

**Comment by danirueda** [comment]
Yeah! It works!

> The reason that there are no errors in the logs is that the file is apparently not sent at all.

All seemed point to that. Excel file loaded without problems! Althout I will user 4.26.0 to be safe because now v4.30.0 is an alpha.

Thank you!

Best regards :smile:

**Comment by jflamy** [comment]
4.30 is the same as 4.29.  The only thing in alpha is the medals scoreboard, so you’d be ok. All the builds run the automated tests for the core engine. 

jfl, de mon téléphone

**Comment by danirueda** [comment]
Ok, better for me because I want to run the [simulation](https://owlcms.github.io/owlcms4/#/Simulation) feature to be calmed knowing all works.

Thanks!

Regards

**Comment by jflamy** [comment]
I created a [4.29.1](https://github.com/owlcms/owlcms4/releases/tag/4.29.1) release with the one-line fix.

**Comment by jflamy** [comment]
Also, in order to run the simulation, your athletes must be in categories. so you will need to provide a bodyweight in your registration file.

**Comment by danirueda** [comment]
Sure! I'll do it. If I have any problem I can't resolve by myself I'll contact you.

Thank you!
