### ISSUE TITLE
Is it possible to create leaderboards where the ranking is calculated by sinlair points and make them visible?

### ISSUE THREAD

**Issue by Gawcyk** [jflamy/owlcms4#498]
Scoreboard (not leaderboards - teanslation bug)

**Comment by jflamy-dev** [comment]
There is already a top Sinclair scoreboard for competitions that award a "best lifter" prize.

If you are talking about a variation on the group scoreboard, one way to make this work would be to have only two categories, male and female, with no weight limits. There would be an additional column with the score.  In this way the scoreboard would reflect what went on in prior groups.

**Comment by jflamy-dev** [comment]
It would also be technically possible to always add two columns with the category-independent score and the rank.

**Comment by jflamy** [comment]
Will probably work on this when I review what is needed for team competitions

**Comment by jflamy** [comment]
See 4.33.0-beta08.  This is a B group in a large competition, so the high numbers on the Sinclair rankings are normal
![8Qyb86WTj9](https://user-images.githubusercontent.com/678663/178639370-ab4d8012-80f6-4d28-8410-cf5932f0595d.png)
