### ISSUE TITLE
Warn when athlete weight causes a change in category

### ISSUE THREAD

**Issue by gal432** [jflamy/owlcms4#499]
Hi, 
We just used the `owlcms4` last weekend in Israel to run our national junior competition, and we discovered that we re-assigned athletes from one group to another, because they were less than the weight they declared when registering for the competition.

This is an invalid case because the athlete needs to be weighted in the group he declared. and if the weight is less - he needs to make sure he goes up on the weight to be in the category. 
We didn't have any warning in the software while the athlete was re-assigned to the new group, and this group already finished for today, and in total - it's not allowed to change the group you are assigned to. 

Can we make settings to block the auto re-assign of an athlete to a new group? if the athlete registered to group X and he weighted less / more, the save of the weight will fail with the proper error message.

Thanks for this amazing project. We felt like we are running an international competition with all the proper screens, timer features, and the judge using mobile devices :)

**Comment by jflamy-dev** [comment]
Note that the competition secretary should always double-check categories and entries.  But I have opened an enhancement request.

**Comment by jflamy-dev** [comment]
Fixed in 4.32.1-rc01
