### ISSUE TITLE
Fixed Round Robin setting

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#501]
Me again :). We're setting up a new Teams competition and want to mimick the German Bundesliga OWL competition. There they use a true Round Robin system; let's say you have 4 groups of 4 lifters each. 16 lifters in total, divided by Group 1 and Group 2 (so you can bring in some pacing and planning/strategy).

We want to use a Round Robin system where the order is Lifter 1, Lifter 2, Lifter 3 up until Lifter 8 doing their lifts after each other. So indeed, everyone will first do S1, then S2 and then S3. But we also want to keep this system, **even if Lifter 3 (who is next in line) lifts less than Lifter 4 (who in a Round Robin system should come after Lifter 3).** We tested this today, and Lifter 4 moved up next in line because his Snatch was lower than the Snatch of Lifter 3.

Could you implement an option to make it a true Round Robin system, even though somebody is moving less weight than the person later than him/her? Because now we have to force (via the Marshall) Lifter 3 instead of Lifter 4.

**Comment by jflamy-dev** [comment]
We don't have such leagues in North America, so I need a bit more.
You're saying that in addition to all 1st attempts being done first, the athletes are free to change their weight at any time, and that they lift according to a strict order -- meaning that the weight can go up or down very dramatically and drive loaders crazy ?
How is the lifting order decided?  Is it the random lot number ?

**Comment by jflamy-dev** [comment]
And I predict the next thing you're going to ask is for some funky formula based on Sinclair, gender, difference between bodyweight and amount lifted, and perhaps age.  How do you score points ?

**Comment by JDFS404** [comment]
The weight is given immediately after the (first) lift and cannot be changed afterwards. That's how we play with it this season.

Also to not drive loaders crazy this way. But in my eyes, this is a true Round Robin setting right?

I don't need no fancy scoring, we just take our European Standard % and doing calculations in separate Google Sheets because we have multiple regions doing qualifiers and only top 2 teams progressing to the Finals (for which the same true Round Robin system is used). It puts a burden on loaders, but here in NL where WL is a semi-amateur sport with a few outliers, there's not going to be dramatic changes in weight between lifters anyway.

**Comment by JDFS404** [comment]
Scoring points we do like this: every team has four lifters and only the top 3 highest lifts count. So let's say every lifter scores 50% of the European standard in their weightclass (that would be approx 164 kg for a M 67, ES is 327), the team scores 150.

At the end of 3 rounds (starting in April, finishing in June), all points are summed and from 4 teams in every region, only the top 2 progress to the finals.

**Comment by jflamy-dev** [comment]
Done.  Lot number is used for lift ordering. Comes after the "group girls first" so if both are checked all girls go first according to lot number, then all men according to lot number, so that there is no need to switch barbells.
In next release after 4.32.2

**Comment by jflamy-dev** [comment]
https://github.com/owlcms/owlcms4-prerelease/releases/tag/4.33.0-alpha00
