### ISSUE TITLE
Down sound/signal with Announcer playing Referee

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#502]
We have some matches in The Netherlands, which are basic club matches but for which we would like to use OWLCMS with one official referee (also playing the announcer). Since not 3 referees are needed in this situation, the Announcer gives a white or red light. We played with this and unfortunately, the Down Signal is not given in the Athlete Facing Screen (only a decision by the middle Referee) and no sound is being played.

Can you add a Setting in which you choose that the Announcer can 'act' as Referee and thus give 3 red/white lights including the Down signal? We now do it with AutoHotkey mapped 1 to 1, 3 and 5 and 2 to 2, 4 and 6 as a workaround...

**Comment by jflamy-dev** [comment]
If you have a single referee facing the athlete,  why can't the referee just say "down" and then click his decision, which everyone will see.  That's how you would handle refereeing with flags anyway.

**Comment by JDFS404** [comment]
We can do that, but we're doing the one man ref competition sometimes with athletes from different countries. Last time there was some confusion when our referee used the Dutch word for down. 

A sound being emitted is clear for everybody right?

Because all other sounds do work (like the 30 seconds left beep), I would really like to have the down signal if the announcer gives a white/red light and thus overruling the referees

**Comment by jflamy** [comment]
The referee should always raise his/her arm and lower it when giving the
down signal. In international meets the tradition is to say «  down » in
English.  The referee should always be ready to use the hand gesture
because it unfortunately happened that wires get unplugged or laptops go
bad or software acts up.
I will check what is involved in adding a setting in the announcer cogwheel
options. The decision sounds do not come from the same user interface
component as the timer sounds
-- 
(Envoyé de mon téléphone mobile.)

**Comment by jflamy-dev** [comment]
Done. Will be in next release (4.32.2 is bug fixes and translations only at this point)

**Comment by JDFS404** [comment]
Thanks so much! FYI: we 'fixed' this this weekend to have an refereeing screen open and an announcing screen at the same time (laptop + external monitor). I made a script with AutoHotkey that mapped `1`, `3` and `5` to a key combination that he liked and vice versa for `2`, `4` and `6`. So once he stopped the clock in the announcing screen, he clicked on the black part of the screen in the refereeing screen (so that the browser would pick up his keystrokes) and then used his key combinations to play for 3 referees at the same time. Once done with that, he went back to the announcing screen.

So I'm glad that we have a workaround for this now :). This also comes in very handy for small club meets, where we want to mimick a real competition including the signals used (such as a down signal) but where we don't have enough volunteers/official referees to act as referees.

**Comment by jflamy-dev** [comment]
https://github.com/owlcms/owlcms4-prerelease/releases/tag/4.33.0-alpha00
