### ISSUE TITLE
24H instead of AM/PM

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#503]
Just wanted to check if it's possible to add a 24-hour notation setting instead of 12-hour notation.

**Comment by jflamy-dev** [comment]
This depends on the locale chosen.  US English uses AM/PM and it is the default on many cloud providers.

I now force 24h format if the language is English and the country is not "old-fashioned" ({"AU", "GB", "IN", "NZ", "PH", "US", "ZA"}).  The program tries to get the country from the operating system if it is not explicitly given.  So running on a laptop usually gives something sensible.  Other countries will get 24h format.

If you are running in the cloud and get AM/PM dates, I suggest you set the OWLCMS_LOCALE environment variable to en_SE (this actually uses English for translation, and Sweden conventions for date/time formatting -- the Swedes follow the international ISO standards).  On Heroku, this is done on the settings page.

This tweak will be available in next release.

**Comment by jflamy-dev** [comment]
See https://github.com/owlcms/owlcms4-prerelease/releases/tag/4.33.0-alpha00
