### ISSUE TITLE
Report new records tentatively broken

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#517]
- [ ] Create new report in same format suitable for copy/paste in existing files
- [ ] Add to final package in suitable format

**Comment by jflamy** [comment]
- [ ] Create new report in same format suitable for copy/paste in existing files
- [ ] Add to final package in suitable format

**Comment by JDFS404** [comment]
Hi monsieur, testing the new Records function! Is it true that the function is broken? I uploaded record files (IWF and EWF and Dutch standards) but they won't show up on the scoreboard even if I make a new world record (I wish!)

![image](https://user-images.githubusercontent.com/26678110/188328812-72186ac1-996f-4c0c-8ec2-91342b4c4340.png)

**Comment by jflamy** [comment]
I created a separate issue for this request.  Issue #517 is a request for a new feature on which work has not started.  Please create new issues when you report a problem.

**Comment by jflamy** [comment]
Discussion will take place in issue #521 please follow there.

**Comment by jflamy** [comment]
Replies have been posted on issue #521
