### ISSUE TITLE
Lifting order scoreboard

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#524]
**Is your feature request related to a problem? Please describe.**
The lifting order screen makes it easier to count attempts in the warm up room, but does not provide the level of detail that the scoreboard provides. For example, you cannot see whether the other athletes have made their previous attempts or how big the jumps were for previous attempts. It's also easier to visually scan the scoreboard to count attempts than to read the words in the Next Attempt column and calculate from there.

**Describe the solution you'd like**
This can be improved by replacing the Requested Weight and Next Attempt columns with the six attempt columns from the scoreboard or by replacing the custom view with the full scoreboard in lifting order.

**Comment by jflamy** [comment]
Frequent request.  Should be straight forward (famous last words)

**Comment by jflamy** [comment]
Lifting order button now opens a full scoreboard in lifting order.

**Comment by jflamy** [comment]
Included in [34.2.0-beta01](https://github.com/owlcms/owlcms4-prerelease/releases/tag/34.2.0-beta01)
