### ISSUE TITLE
Announcer: Display all six attempts for current athlete

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#525]
**Is your feature request related to a problem? Please describe.**
As an announcer, it's useful to see all six attempts for the current athlete in order to provide better commentary. The current announcer screen only displays the current weight and the attempt number. Having to also look at the scoreboard, or manually click on the athlete's row to see their attempt card is cumbersome.

**Describe the solution you'd like**
Display the six attempts, with color indicators just like the scoreboard, at the top of the announcer screen.

**Comment by jflamy** [comment]
Not a straightforward change. Will likely require a not so elegant bit of cleverness (aka kludge).

**Comment by jflamy** [comment]
Looks easier with new Vaadin version.  Attempting.
