### ISSUE TITLE
Option to remove referee decision delay when entered by announcer

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#526]
**Is your feature request related to a problem? Please describe.**
When the referees are not using devices that directly control OWLCMS, the announcer can enter the referee decision. However, when this is done, the delay between decision and display still exists, which causes the decisions to take an unnecessarily long time to show up compared to when the actual referees made their decision.

**Describe the solution you'd like**
Add an option to allow the decision to take effect immediately when entered by the announcer.

**Comment by jflamy** [comment]
Left is as optional for now. Will be in next build.

**Comment by jflamy** [comment]
Reopening.  Default should be immediate.

**Comment by jflamy** [comment]
Changed the default to be immediate, except when referee is in solo mode and down signal is shown.
