### ISSUE TITLE
Update USAW results output

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#527]
**Is your feature request related to a problem? Please describe.**
USAW has switched to using the BARS system for submitting results. The current export does not match the format used by BARS.

**Describe the solution you'd like**
Update the USAW results format to use https://www.teamusa.org/-/media/USA_Weightlifting/Documents/Membership/2020/USAWResultsTemplate.xlsx

**Comment by jflamy** [comment]
I had sent a BARS format to the mailing list for validation but no-one replied.
See files enclosed.  

- Note that the spreadsheet has one additional column so I can map the age group as labeled by owlcms to the verbose name used by the BARS spreadsheet.  So depending on how their reader works (whether it reads only the columns it knows about or not) the output may work as is or not.  If it doesn't work, well a single cut-and-paste will.
- You need to use the enclosed age groups file for the boundaries to match what BARS expects

So
[USAWResultsTemplate.xls](https://github.com/jflamy/owlcms4/files/9700532/USAWResultsTemplate.xls)
[USAW-AgeGroups.xlsx](https://github.com/jflamy/owlcms4/files/9700536/USAW-AgeGroups.xlsx)

**Comment by jflamy** [comment]
The files go under local/templates/protocol and local/agegroups respectively.  You need to load the age groups file and reallocate the athletes.  I could in theory load add a _en_US locale to the file and make it load automatically on first run, but cloud providers tend to run under that locale so I have no surefire way of guessing.

**Comment by jflamy** [comment]
If the files work out I will add them to the distribution.

**Comment by scottgonzalez** [comment]
I'll see if I can get this tested with BARS.

I did notice that the weight classes are not correct for at least one of the age groups. I'll go through and check all of them later and provided an updated file.

I also noticed that the results spreadsheet has a broken value for the Age Category column for master's women. This is because the Results sheet uses `W35` while the Validation sheet uses `F35`, so the `VLOOKUP` fails. I assume this should be an update in the age groups spreadsheet to change the codes to use `F`?

**Comment by jflamy** [comment]
I recently changed the Masters groups to have W as in the Masters's rule book.  So yes, try changing the F for W on the validation tab.

**Comment by jflamy** [comment]
(for clarity, it should be W35 throughout).  F35 is a relic.

**Comment by scottgonzalez** [comment]
I've updated both templates locally and generated a new results sheet. I just emailed that to Pedro Meloni, USAW's Director of Events, for testing.

**Comment by Toolazy2work** [comment]
1. I just came here to make the same request, so thank you @scottgonzalez  for already making it and for @jflamy for already addressing it!
2. I just learned there is a mailing list!

**Comment by jflamy** [comment]
Mailing list is owlcms on Google Groups

**Comment by jflamy** [comment]
> I've updated both files locally and generated a new results sheet. I just emailed that to Pedro Meloni, USAW's Director of Events, for testing.

Scott, care to post the updated files here ?

**Comment by scottgonzalez** [comment]
Here are the updated files. I still haven't been able to confirm that the generated results are accepted by BARS. I'll keep trying to get access. At least the age groups should be correct.

[USAWResultsTemplate.xls](https://github.com/jflamy/owlcms4/files/9908098/USAWResultsTemplate.xls)

[USAW-AgeGroups.xlsx](https://github.com/jflamy/owlcms4/files/9908099/USAW-AgeGroups.xlsx)

**Comment by jflamy** [comment]
I have fixed missing bodyweight categories to the agegroups file (first tab) and added instructions on how to remove formulas from the owlcms-generated output.  Will be in the stable 34.4.0 release.
In the mean time, here are the updated files.
[USAW-AgeGroups.xlsx](https://github.com/jflamy/owlcms4/files/9912297/USAW-AgeGroups.xlsx)
[USAWResultsTemplate.xls](https://github.com/jflamy/owlcms4/files/9912298/USAWResultsTemplate.xls)

**Comment by jflamy** [comment]
Note that the age groups file has the Open categories enabled by default.  So a U13 36kg will show up in the open category as well.  Maybe the open categories should not be enabled?

**Comment by jflamy** [comment]
That is actually the case for the results - the most specific category will be used.
But with respect to the actual meet, with the age group file as it currently stands a 13 year old will be shown as eligible for the Open medals.  Not sure that is what is intended -- looks odd when looking at the registration page.

**Comment by Toolazy2work** [comment]
I thought that U13 ARE eligible for open medals.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jflamy** [comment]
Then so be it, that's what's in the file.  Included in 34.4.0-rc02 will also be in stable release.

**Comment by Toolazy2work** [comment]
Jean-François, you’re amazing.  Thank you for giving the community an incredible piece of software to bring our sport to modern times!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
