### ISSUE TITLE
Unique Results Package

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#529]
**Is your feature request related to a problem? Please describe.**
When downloading the final results package for a meet, athletes that qualify for multiple categories are included in the results multiple times. This can be confusing to look at and may cause issues if the results package is being used to update a system that is expecting an athlete to only have one result.

**Describe the solution you'd like**
I would like to have a results package that only contains one entry per athlete, with the athlete in the most specific category.

**Comment by jflamy** [comment]
If you want the 6 attempts with athletes shown only once, in the native category, use the Group Results page, with the 6 attempts template.  That's the old vanilla-flavored style.

The final package is meant to show all the rankings for a competition and to show team scores.  If the competition is multi-age-group, the same athlete has different rankings, and may have been part of several age group teams, scoring points in each age groups.

**Comment by scottgonzalez** [comment]
Ah, ok. So this is just a matter of me using the wrong results screen.

**Comment by jflamy** [comment]
Once upon a time, I had no result sheet that would show the results for a
single category, at the end of a competition, and people were selecting a
part of the results package and printing that.

So in a way, the category results sheet is a subset of the final rankings.

A better name for the page  would probably be Final Results, with Category
Results an option.
