### ISSUE TITLE
iFrame support + update

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#543]
**Is your feature request related to a problem? Please describe.**
Want to have proper iFrame support with updates in the script reflected in iFrame as well.

We want to broadcast via https://alpercoaching.com/livestream.html with the Public Results front-end, but since it has to be embedded into an iFrame it would be good to have it update as well (it won't now).

Is this possible? In the future, we would like to broadcast more with Public Results in it as well.

**Comment by jflamy** [comment]
I have no idea why the Push feature I use to force the updates is not working inside an iframe.  As such, I have absolutely no idea on how to make it work, or if it can be made to work.   I have opened a question on the Vaadin StackOverflow https://stackoverflow.com/questions/74225836/why-is-push-not-happening-inside-an-iframe (but honestly I'd be ever so surprised to get an answer).

**Comment by jflamy** [comment]
I will also try their Discord chat, but again, so few people are using iframes nowadays that I'd be amazed if anyone bothers to dig in.

**Comment by JDFS404** [comment]
Thanks a lot, we now injected JS to update the iFrame every x seconds. If you're interest, tomorrow (CEST) around 10h we will start a 2-day competition and using the current athlete display (which is now without password!) and the scoreboard via this link: https://alpercoaching.com/livestream.html

**Comment by jflamy** [comment]
Can you e-mail me your recipe for injecting the JS?  If the livestream shows the attempt board on video then it's not so bad -- otherwise you might miss the decisions being shown.

**Comment by JDFS404** [comment]
Yes, current athlete display is streamed via OBS and this is the code we're injecting now:
```
<iframe id="scoreFrame" width="100%" height="100%" src="https://mylink/results?silent=true&fop=A" frameborder="0">
</iframe>
```

This one is ofc not difficult, and this one for the refreshing of the iFrame:
```
      <script>
         window.setInterval("reloadIFrame();", 10000);
         
         function reloadIFrame() {
           document.getElementById("scoreFrame").src="https://mylink/results?silent=true&fop=A";
         }
      </script>
```

**Comment by jflamy** [comment]
Just being dense this morning.   I would expect that the alpercoaching page asks for a URL to put in its iframe.  Where does the JS injection take place ?

**Comment by JDFS404** [comment]
after the <div> section, just before the end of </body>, not some fancy things going on.

```  <body>
      <div class="container-fluid">
         <br>
         <br>
         <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
               <img class="logo" src="https://alpercoaching.com/images/logo.png" alt="">
            </div>
            <div class="col-md-4"></div>
         </div>
         <br>
         <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="height:35vw">
               <iframe width="100%" height="100%" src="https://www.youtube.com/embed/Cshh_MeShpQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="col-md-2"></div>
         </div>
         <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="height:35vw">
               <iframe id="scoreFrame" width="100%" height="100%" src="https://link/results?silent=true&fop=A" frameborder="0" ></iframe>
            </div>
            <div class="col-md-2"></div>
         </div>
      </div>
      <script>
         window.setInterval("reloadIFrame();", 10000);
         
         function reloadIFrame() {
           document.getElementById("scoreFrame").src="https://link/results?silent=true&fop=A";
         }
      </script>
   </body>
</html>```

**Comment by jflamy** [comment]
So you actually have control over that site, it's not a service you are using ...

**Comment by JDFS404** [comment]
Ah yes - maybe I forgot to mention that - I'm basically a one-man-show at this moment rolling out OWLCMS (fortunately the TOs know how the software work, but also not all of them) and proxy-ing it etc. Next step for me would be to inject the Scoreboard on our own National WL Site in a Livestream page where we also will use this code to update the scoreboard, but making sure the Current Athlete display will be streamed for real-time info.

**Comment by jflamy** [comment]
I will be creating a variation of the scoreboard that has the group info at the top, and not the athlete.  The kind of scoreboard you would use on TV or a stream when not showing the athlete.  If the attempt board is visible on the live screen, then that would be perfect.

**Comment by jflamy** [comment]
Can you go to the stackoverflow issue https://stackoverflow.com/questions/74225836/why-is-push-not-happening-inside-an-iframe  and answer the question about how the site behaves ?  (e.g. if you click on the iframe, does the dialog come up and are you able to switch the colors from dark to light ?
