### ISSUE TITLE
Add "File version" in installer -> Details

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#552]
**Is your feature request related to a problem? Please describe.**
No, its not problem, just a feature request

**Describe the solution you'd like**
While "Product Version" is present (example 34.3.0), the "File Version" shows as 0.0.0.0

**Describe alternatives you've considered**
No Alternative, its kinda a Yes or No

**Additional context**
![image](https://user-images.githubusercontent.com/2252852/199377854-097f2c50-693f-476a-9b16-d419bc37a8b2.png)

**Comment by Toolazy2work** [comment]
Again, this is like the LOWEST PRIORITY.  Feel no stress with this ask

**Comment by jflamy** [comment]
The program used to create the installer seems to do pretty much what it wants with the instructions it is given.  What is shown isn't what is being asked -- the file version text ends up being shown as the product version.  The fileVersion and productVersion parameters must be numbers, I have no convenient way to have that given that I follow semantic versioning guidelines with prerelease tags.
```
                            <versionInfo>
                                <fileVersion>1.0.0.0</fileVersion>
                                <txtFileVersion>${project.version}</txtFileVersion>
                                <fileDescription>${project.name}</fileDescription>
                                <copyright>Jean-Francois Lamy</copyright>
                                <productVersion>1.0.0.0</productVersion>
                                <txtProductVersion>1.0.0.0</txtProductVersion>
                                <productName>${project.name}</productName>
                                <companyName>...</companyName>
                                <internalName>owlcms</internalName>
                                <originalFilename>owlcms.exe</originalFilename>
                            </versionInfo>
```

**Comment by jflamy** [comment]
I will add the project version as the txtProductVersion as I suspect they just swapped the labels.

**Comment by jflamy** [comment]
@Toolazy2work send email to jf_at_jflamy.dev to briefly introduce yourself, I like knowing a bit more about the faithfuls :-)

**Comment by jflamy** [comment]
As it turns out, the program that builds the installer requires values for the fileversion and copyright fields, but does not actually include them in the output.  So case closed.

**Comment by Toolazy2work** [comment]
An alternative I can request (again, NOT a big deal, don’t spend too much time on this), but can we include the version in the file name for the installer?  As someone who has a bunch of installers in my downloads folder, it would help to have the version somewhere.  Not a big deal, just if it’s easy.

**Comment by jflamy** [comment]
I'll have to experiment with the Azure Devops task that pushes to GitHub.  When I next need to go there.

**Comment by jflamy** [comment]
Installers have the version number in 3.35.0-alpha05.

**Comment by Toolazy2work** [comment]
You’re amazing!  Thank you so much!
