### ISSUE TITLE
Summon referee bug(s)

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#570]
If the jury tries to summon a referee while the down signal is being shown, they get an error message saying that they cannot summon a referee while the down signal is being shown while simultaneously getting a message that a referee has been summoned.

It also appears that the i18n lookup is failing even though I'm in the default `en` locale.

<img width="1293" alt="Screen Shot 2022-11-21 at 9 14 12 PM" src="https://user-images.githubusercontent.com/141167/203200867-6658a71d-721d-491b-8694-4397b65296ce.png">

**Comment by jflamy** [comment]
Missing entry in translation file. 
Notification is probably sent out of order before the deed is done.

**Comment by jflamy** [comment]
Fixed in 35.0.0-beta07.  You may pull.
This one was trickier, stumbled on several edge cases.   I offered food to the Regression deities.
