### ISSUE TITLE
Incorrect clock button state

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#575]
If a clock start MQTT message is received wile the clock is already running, owlcms correctly ignores the MQTT message and displays an error message on screen. However, the clock button state reacts as if the clock had stopped (the play button turns green and the stop button turns gray).

**Comment by jflamy** [comment]
Simplest fix is ignoring.
```
13:37:30.529 DEBUG FOP A    ignoring start clock when clock is running. 
```
