### ISSUE TITLE
Counter-intuitive Record Eligibility rule

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#592]
U15 and JR joint competition.
U15 are NOT eligible to compete as JR (in effect, not a true JR, rather a 16-20 group).  *But* U15 should be eligible to beat JR record (not likely, but...)

Under current record eligibility check, the JR record cannot be beaten by U15 because he is not eligible to JR age group.

Several workarounds are possible, but they are not intuitive (ex: name the record age group "junior" instead of "jr".

**Comment by carlosmoracampos** [comment]
Really, we must consider that, independent our criteria, an U15 athlete in a official competition (U15 in not recognized by IWF but PAWF) can compete in a JR competition if he/she has 15 years old (calendar year).  Then, if his/her performance is high, has possibility to set a RECORD, in dependence of competition type.
So, another issue is the ELEGIBILITY, because an athlete may be consider like elegible in twice competitions, or not.
Good discussion.

**Comment by jflamy** [comment]
The original problem was with Masters.  Many federations have a joint Senior+Masters championship.  The problem is how to decide whether 35-year old senior can break the Masters record (or not).  There are several issues
 - in Canada, you must be a member of the Masters affiliated association to break a Masters record
 - sometimes, you must break the Masters record in a Masters competition.  If you decided to lift in the morning with the Masters, that would be ok (it is considered to be a Masters federation event)  but not if you lift in the afternoon inside the senior group (that is not considered to be Masters event).

The simplest idea seems to be to use the federation codes.
- if eligibility depends on masters membership, use a different code for the federation.
- Then you can mark all the morning group participants as masters
- and if dual-membership athletes lift in the afternoon, either mark them as eligible in both federations, or only as a senior.

Under that criterion, there is no longer a need for the age group eligibility restriction, which is actually inappropriate for overlapping age groups.

**Comment by carlosmoracampos** [comment]
Yes, elegibility is the answer.  One athlete compete and has oportunity to brake records in dependence of in how many events is consider elegible, like Lima competitions.
