### ISSUE TITLE
Personal records

### ISSUE THREAD

**Issue by Jartukainen** [jflamy/owlcms4#636]
**Is your feature request related to a problem? Please describe.**
It would be nice to have personal records to be shown for the announcer

**Describe the solution you'd like**
As a registration page, it would be nice to have a three slots for individual records in official competitions under IWF rules for sn. c&j and total.

**Describe alternatives you've considered**
Or even better if you can upload registration sheet, where you three extra columns for them.

**Additional context**
This might only needed in club level competition but also nice info, while streaming competition to socialmedia platform, it would have boost for audience and make chat more live.

**Comment by jflamy** [comment]
- adding fields is straightforward
- registration sheet is getting a bit large, will eventually need to do something about it
- toughest part is modifying how records are displayed.
- I would not use the "record attempt section" - I believe the color highlight inside the box is enough.

**Comment by jflamy** [comment]
Available starting with version 38.1.0-alpha04 or more recent
https://github.com/owlcms/owlcms4-prerelease

**Comment by jflamy** [comment]
The only way to enter the PBs is on the athlete editing page.  Will see if I can add to the registration page.

**Comment by jflamy** [comment]
#642 opened for registration sheets

**Comment by jflamy** [comment]
importing and exporting personal bests using the Excel sheets now available starting with 38.1.0-alpha05
