### ISSUE TITLE
Records - Setting a new record versus hitting the standard

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#648]
**Describe the solution you'd like**
Is the software already taking into account whether you set a new record (+1) or hit the standard? Are there certain parameters to be set to make a difference?

**Comment by scottgonzalez** [comment]
Standards are just like any other existing record, they must be exceeded by at least 1kg for a new record to be set. Matching the standard does not count as setting a new record.

**Comment by scottgonzalez** [comment]
Yes, this is documented on the IWF site at https://iwf.sport/wr-explanation/:

> Since the record figures have been scientifically created in a mathematical process, and do not represent the actual achievement of an athlete, it was agreed to call them World Standards until an athlete exceeds them by a minimum of 1 kg.

You're not alone in the assumption that meeting the standard would set a new record though. I believe at last year's world championships even the commentators were confused about this when an athlete met one of the standards on their second attempt.
