### ISSUE TITLE
Include USAW / Individual Federation Number in results spreadsheet

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#649]
It would make life so much easier if the USAW numbers (or whatever federation number for individuals) was included in the results package.  This way we can copy and paste all the information (or script it) to the bulk upload spreadsheet for a meet.

**Comment by scottgonzalez** [comment]
There's already a specific template for USAW results. Use the category results download.

![Screenshot 2023-03-31 at 4 29 47 PM](https://user-images.githubusercontent.com/141167/229223600-59d3c0d5-cb1a-40f2-961d-763a1dcfeb2b.png)
