### ISSUE TITLE
Weigh-in Page doesnt load

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#650]
**Describe the bug**
When navigating to the weigh-in page, nothing loads.  Had to input numbers by editing peoples registration

**owlcms version**
version 4.38.2

**To Reproduce**
1. Go to weigh-ins
2. Page navigates to weigh-ins, shows in URL, but page is blank

**Expected behavior**
I am expecting to see a screen where we can edit weigh in numbers and opening lifts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version Version 111.0.5563.112 (Official Build) (64-bit)

**Additional context**

**Comment by jflamy** [comment]
Cannot reproduce in 48.3.
Please provide log file and database.

**Comment by jflamy** [comment]
Please test with 38.3.1-rc01

**Comment by Toolazy2work** [comment]
Ok, just tried to reproduce with screenshot and i also could not reproduce.  Please mark closed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
