### ISSUE TITLE
New Sessions have 0kg for all completed lifts

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#651]
**Describe the bug**
All sessions had 0s for the completed lifts.  This was rectified by removing the zeros from each lift

**owlcms version**
version 4.38.2

**To Reproduce**
1. Go to announcer
2. Session is already done

**Expected behavior**
When navigating to announcer, its expected that no lifts had yet been completed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 111.0.5563.112 (Official Build) (64-bit)

**Additional context**

**Comment by jflamy** [comment]
Please try 38.3. Cannot reproduce that problem on that version myself. 
Could be tied to the specific way you loaded data, if still present as a bug.

**Comment by jflamy** [comment]
Should be fixed in 38.3.1-rc01
