### ISSUE TITLE
Screen Displaying incorrect weight

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#652]
**Describe the bug**
the main display screen was showing the incorrect weight.  This only seemed to affect lifters with '/' in their team name.  upon reload of the page, would get an error, indicating it cant load the image with the '/' in the name.  Recommend to sterilize the team name input to not allow this character

**owlcms version**
version 4.38.2

**To Reproduce**
1. Run event like normal.
2. Have lifter go who has a / in the team name
3. weight doesnt change on main display

**Expected behavior**
It should show the correct weight

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 111.0.5563.112 (Official Build) (64-bit)

**Additional context**

**Comment by jflamy** [comment]
Normally User interface kit does sterilization. Will investigate!

**Comment by Toolazy2work** [comment]
I have a screenshot, just not handy at the moment.  Ill post it this evening.

**Comment by jflamy** [comment]
No need for the screen shot this one is obvious. I will need to document that / will be sanitized to _  to make it workable as a file name.

**Comment by jflamy** [comment]
Should be fixed in 38.3.1-rc01
