### ISSUE TITLE
Inappropriately setting 2:00 clocks

### ISSUE THREAD

**Issue by Toolazy2work** [jflamy/owlcms4#653]
**Describe the bug**
OWLCMS was inappropriately setting the clock for 2 minutes.  we were able to manually set the clock when needed

**owlcms version**
version 4.38.2

**To Reproduce**
1. Run a meet like normal
2. Sometimes, the clock doesnt set properly and will set for 2 mins vs 1 min

**Expected behavior**
The clock should only be set for 2 mins when a lifter is following themselves, but this didnt seem to be the case.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 111.0.5563.112 (Official Build) (64-bit)

**Additional context**

**Comment by jflamy** [comment]
Please provide more context. At least the log file. A bug was fixed in 38.3 regarding the 2:00 clock but it would only occur if the announcer entered the decision.

**Comment by Toolazy2work** [comment]
Oh, we only did announcer decision, so this may be resolved.

**Comment by jflamy** [comment]
Likely.
