### ISSUE TITLE
FLIC2: Problem with Announcer screen programmable shortcuts

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#667]
Is it possible to give the same shortcuts (unless `.` and `,` have different functions) to start or stop the clock? We run the clock from the Announcer screen 9/10 times and it would be great if we could program buttons for the Announcer as well to start or stop the clock without looking at the screen. Reason being is that sometimes we're short of referees and the Announcer is the third referee as well (I've been in that situation a couple of times).

**Comment by jflamy** [comment]
Actually the announcer normally never enters decimals, so that might work.  Looking into it.

**Comment by JDFS404** [comment]
Great! Would it also be in line of expectations to have something similar for the 1 and 2-minute buttons? Perhaps `[` and `]`? In that way, we could map them to a USB-controller as well :)

**Comment by jflamy** [comment]
Yes, https://www.w3.org/TR/uievents-code/#key-alphanumeric-writing-system indicates that the brackets can be used without ambiguity.
Added to the announcer and timekeeper screen.  Will show up in next release.

**Comment by JDFS404** [comment]
Would it also be possible to map a keyboard shortcut as a toggle, so I can map one Flic button as a push device to basically toggle the clock? Perhaps `\` or another button which is not in use?

**Comment by jflamy-dev** [comment]
Urk.  `.` is already used, so I would suggest `/`.  I will see what I can do for toggling.  Due to current behavior, the toggle would probably be yet another key, maybe `=` (assuming there is a simple way to implement, what should be simple sometimes isn't.

**Comment by JDFS404** [comment]
Thanks a lot Monsieur Lamy, perhaps a moment to remap `[` and `]` to `-` and `+` as well so we can map it?

**Comment by jflamy** [comment]
Can't use `-` because it is actually used by the announcer to cancel a lift (-90 is no lift 90)

**Comment by JDFS404** [comment]
Perhaps `+` for 2 minutes and `*` for 1 minute, and `=` for Toggle? It doesn't really matter to me which one is which, as long as I can map it 😄

**Comment by jflamy** [comment]
Flic is a pain.   For the program, I need to use what's on the keycap (the bottom symbol) and then tell it the key modifier if I need Shift.  So so far I avoided modifiers.

. for stop
/ for start
- for 1 minute
= for 2 minutes

* would be toggle

**Comment by jflamy** [comment]
As it turns out, `*` as sent by Flic is the numeric keypad `*`.   I have added both `SHIFT`+`DIGIT_8` and the numeric multiply as shortcuts for toggling.

**Comment by jflamy** [comment]
Available in [38.5.3-rc00](https://github.com/owlcms/owlcms4-prerelease/releases/tag/38.5.3-rc00)

**Comment by jflamy** [comment]
As it turns out `-` cannot be used.  The only key left to use is `+` which the Flic sends as NumPad Add.
So I added Shift= and numpad_add as shortcuts to reset to 1 min.
Fixing the documentation and adding to the release notes.

**Comment by JDFS404** [comment]
I tried it - with my keyboard from my Windows machine I'm able to use the shortcuts, however not with the Flic button. Only for the 1 min clock via `+`

**Comment by JDFS404** [comment]
> I finally found a Flic2, managed to reset it, and managed to pair it with one of my laptops (my main laptop refuses to see it).
> 
> Well, never be certain of anything. It appears that the Flic2 sends the Numeric Keypad variations of the characters. On my North American laptop, Flic2 "." is seen as NUMERIC_DECIMAL (code 110) and Flic2 "/" is seen as NUMERIC_DIVIDE (code 111).
> 
> Please go to the site "https://toptal.com/developers/keycode" and confirm these values.
> 
> I will create a 46.0.0-beta06 in https://github.com/owlcms/owlcms4-prerelease/releases in a few minutes with the additional shortcuts. So you should use "." on the Flic2 to stop the clock and "/" to start it.
> 
> The updated list of shortcuts is as follows -- it appears you want the NUMPAD ones.
> 
> ```
> UI.getCurrent().addShortcutListener(() -> doStartTime(), Key.COMMA);
> UI.getCurrent().addShortcutListener(() -> doStartTime(), Key.SLASH);
> UI.getCurrent().addShortcutListener(() -> doStartTime(), Key.NUMPAD_DIVIDE);
> 
> UI.getCurrent().addShortcutListener(() -> doStopTime(), Key.PERIOD);
> UI.getCurrent().addShortcutListener(() -> doStopTime(), Key.NUMPAD_DECIMAL);
> 
> UI.getCurrent().addShortcutListener(() -> doToggleTime(), Key.DIGIT_8, KeyModifier.SHIFT);
> UI.getCurrent().addShortcutListener(() -> doToggleTime(), Key.NUMPAD_MULTIPLY);
> 
> UI.getCurrent().addShortcutListener(() -> do1Minute(), Key.EQUAL, KeyModifier.SHIFT);
> UI.getCurrent().addShortcutListener(() -> do1Minute(), Key.NUMPAD_ADD);
> 
> UI.getCurrent().addShortcutListener(() -> do2Minutes(), Key.EQUAL);
> UI.getCurrent().addShortcutListener(() -> do2Minutes(), Key.NUMPAD_EQUAL);
> ```

I just tested the beta - it works for start stop! It's not yet working for `=` aka 2 min clock. On JS this gives me 187 (but with or without modifier it's the same). perhaps we can also do another shortcut for the 2 min clock? This will complete our announcer buttons as well:
![image](https://github.com/jflamy/owlcms4/assets/26678110/e64ae703-e1db-4009-9add-dd10ec5f65c1)

**Comment by JDFS404** [comment]
Hi @jflamy any luck for the 2 min clock?

**Comment by jflamy** [comment]
There is a shortcut for = and it does work with a regular keyboard.  However Firefox and the other browsers don't send the same code.  My battery in my Flic2 is dead -- I have others in a box somewhere that I need to find and investigate.

**Comment by jflamy** [comment]
Got new batteries. The Flic2 sends the code for NUMPAD_EQUALS when the `=` shortcut is used.   Also added `;` as a shortcut.
Please test 47.0.0-alpha03  (you can ignore the dire warnings at the top -- there are no crazy changes in this release)

Updated the documentation 

##### Shortcuts

> For shortcuts, the keys given are the key locations for a US keyboard. You will need to press the key at the [location shown on this diagram](https://kbdlayout.info/kbdus), no matter what is actually printed on your keyboard.

The clock can be started by using the `,`  (comma) or `/` keys on the keyboard.  The `/` key on the numeric keypad also works. On the Flic2 buttons, this is the `/` shortcut.

The clock can be stopped by using the `.`  (period) key on the keyboard.  The decimal fraction character on the numeric keypad should also work (in many countries, the numeric keypad shows a `,` instead of a `.` to match the local usage for decimal fraction). For the Flic2 buttons, this is the `.` shortcut.

The clock can be reset to 1:00 by using the + key on the keyboard (more precisely, the key combination that corresponds to + on a US keyboard, that is, Shift=).  Using the + key on the numeric keypad will also work. On the Flic2 buttons, this is the `=` shortcut.

The clock can be reset to 2:00 by using the `=` or `;`key on the keyboard ).  Using the + key on the numeric keypad will also work. On the Flic2 buttons, this is the `=` or `;` shortcut.

**Comment by JDFS404** [comment]
Just tested - it works perfectly :) Thank you for doing this for us, now we have a full announcer setup as well next to the referee buttons. This makes the comp for the announcer also easier to focus; no need to have to look at the screen every time to pause the clock! I think it's perfect to migrate to the production version!

**Comment by jflamy** [comment]
I will add it to 46 that is on the doorstep. No plan to move it back to 45.
