### ISSUE TITLE
Add "visiting athlete"/"member of foreign federation" button to weigh-in for athletes not eligible for medals

### ISSUE THREAD

**Issue by ctvulft** [jflamy/owlcms4#670]
Concerned that the new weigh-in feature designating athletes as ineligible for medals will inadvertently make athletes who are ineligible for medals but not competing as members of foreign federations unable to place, score team points, win other awards (best lifter, etc.).

This is an issue under the current USA Weightlifting national events policies (https://www.teamusa.org/-/media/USA_Weightlifting/Documents/Policies/USAWeightliftingEventsPolicies_082922.pdf?la=en&hash=5EBDF707E1318DA9A7DEFCAF6F3ED8365CCCF8B7), where some members of USA Weightlifting are ineligible for medals on the basis of their immigration status (e.g. non-Citizens) but are not competing as members of another federation. By having the "ineligible for medals" button drop them from placing, it also treats them the same as visiting athletes from another federation, penalizing their team by making them show up as scoring 0 team points in the team competition, removing them from competition for other (non-medal) awards.

The current policies describe the placement as staying the same but the medal transferring to the next highest placed athlete.

Hoping addition of a "visiting athlete" or "member of foreign federation" button on the weigh-in form might support making this distinction (the next US national event starts at the end of June...). This is really what the current button represents. Just "ineligible for medals" is more of a cosmetic change to the results.

**Comment by jflamy** [comment]
Ineligible for medals was previously translated as "not eligible for individual rankings" which I felt was a bit longish.

I am quite willing to revert to the previous wording.
The French words "hors-concours" and Spanish "fuera de la competencia" are used, and I was just looking for shorter in English.

The setting is meant for athletes that don't make weight in their category and are still allowed to lift, or for athletes that (like are there for the purpose of qualifying to some other event (like Azerbaidjan in the 2023 African Championship, or some Spain athletes in the last 2023 PanAms).

In such circumstances, the athletes don't get ranked and don't get medals, even though the result they posted at that body weight can count as qualification for later events.

**Comment by jflamy** [comment]
(in my national federation, "invited" meant exactly that, a "foreigner" competing for himself and not having an impact on any of the rankings)
You first have to be eligible for individual rankings to be ranked in the various categories you are eligible to (e.g. JR, SR) and then points are added according to your membership (you could have been nominated to the JR team but not the SR).

**Comment by jflamy** [comment]
I you rank first in your group, score points for your team, and just are deprived of the medal but not of the points, then the program won't handle that.  The scoreboard shown behind the podium may very well show the gold medal winner being ranked number 2, since that's what was used to compute his points for his team.

**Comment by jflamy** [comment]
I am proposing "Lifting out of competition (no points, no medals)" as the checkbox.
Please contact me via e-mail at jf@jflamy.dev so I can get a bit more background.
