### ISSUE TITLE
Support for Modified Attempt Clocks for Adaptive Athletes

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#678]
**Is your feature request related to a problem? Please describe.**
Some adaptive athletes receive additional time (usually one extra minute per attempt) on their attempt clock. Manually adjusting a one minute clock to two minutes is easy enough, but there is no good solution for adjusting a two minute clock to a three minute clock. In addition, automated adjustments to the clock would be preferred.

**Describe the solution you'd like**
Athletes should be able to be marked as receiving additional time. The adjusted time should automatically be applied to all attempts for these athletes.

**Describe alternatives you've considered**
Manually adjust the clock using the one minute and two minute resets.

**Additional context**
Since each federation can have different rules about adaptive athletes, we may need to either track the additional time directly on the athlete or allow for defining types of adaptive athletes and associate the extra time against the type.

This could also be defined and loaded in via files just like age groups and weight classes.

**Comment by jflamy-dev** [comment]
Would probably need to add an "adatptive class".  Canada has 8, with different allocations for time -- only one of the classes gives more time.  Not sure if there are adaptative Masters (with two types of compensations, one for age, one for para-challenge).

**Comment by jflamy** [comment]
usaw does not change the clock
