### ISSUE TITLE
Duplicate MQTT config response

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#684]
**Describe the bug**
When an `owlcms/config` message is published, owlcms sends duplicate responses if there are multiple platforms.

**owlcms version**
version 40.0.0-beta02

**To Reproduce**
1. Set up multiple platforms.
2. Publish `owlcms/config` message.
3. See one `owlcms/fop/config` message published for each platform.

**Expected behavior**
Only one `owlcms/fop/config` message is sent in response to an `owlcms/config` message.

**Additional context**
`MQTTCallback` is intended to be platform-specific, but the config message is system-wide. As a result, each platform has its own `MQTTCallback` instance listening for, and responding to, config messages. This results in duplicate responses. This is more of a minor annoyance than a bug.

**Comment by jflamy** [comment]
Documented the redundancy.  It is now a feature.  Much easier for client to ignore all but first reply than to try to coordinate the monitors (there is one thread per platform).
