### ISSUE TITLE
Feuille de match par équipe

### ISSUE THREAD

**Issue by alupa15** [jflamy/owlcms4#691]
Bonjour,
Serait-il possible de créer un scoresboard par équipe avec un suivi du nombre de point IWF en direct, c'est à dire que le score évolue en fonction des barres réussit et non en fin de match.
Comme Ci-joint : http://scoresheet.ffhaltero.fr/scoresheet/team/competition/view/5078
En France, nous avons des compétitions par équipe comme cela.
Utilisateur depuis 2019, il nous manque juste cette fonctionnalité pour utiliser le système tout le temps au CA Lorient
Je vous remercie,
Sportivement,

**Comment by jflamy** [comment]
C'est noté.  
Je note avec amusement que ce qui est appelé en France le score IWF est en fait le score Sinclair -- l'IWF n'a jamais entériné le score Sinclair, et utilise en fait un autre score appelé Robi -- bref ça n'a rien à voir avec l'IWF.
La portion intéressante est de voir comment les scores mixtes (H/F) utilisés dans certaines de vos régions pourraient figurer.
Et éventuellement les scores utilisant d'autres systèmes (par exemple % du record national utilisé aux Pays-Bas, Robi utilisé en Hongrie, Handicap utilisé en Allemagne pourraient être intégrés)

**Comment by jflamy** [comment]
En passant, il existe un tableau de résultats en temps réel par équipe, lequel montre le total Sinclair par équipe.  C'est pas la feuille de match "scoreboard", mais ça peut intéresser le public.

**Comment by alupa15** [comment]
Ah oui ok, j'avoue avoir déjà entendu parlé du robi point mais en France, il n'est pas utilisé. Il a l'air plus égal lors de match H/F.
En France, nous avons la coupe de France senior Mixte avec 3H/3F et on prends chacun son sinclair. 
Peut-être avoir un choix sur le type de score à afficher sur le scoreboard.

**Comment by jflamy** [comment]
Le Robi se voulait plus égalitaire car les Sinclair H et F ne sont pas
comparables entre eux, ce que le Robi prétendait faire, mais n'y arrive pas
tout à fait non plus.  Pour le commun des mortels, il suffirait de prendre
le poucentage du record du monde ou du record national et ça ferait tout
aussi bien l'affaire.

**Comment by alupa15** [comment]
Oui c'est vrai mais ce tableau ne se mets à jour qu'à la fin du plateau et pas a chaque essai. Comme nous avons souvent des matchs hommes puis femmes, je pense que le système mélange les résultats des hommes et des femmes.

**Comment by jflamy** [comment]
Les tableaux Sinclair sont en temps réel.  Car le score Sinclair ne peut reculer.  Inversement, les tableaux par pointage d'équipe spnt à la fin de la catégorie, car on peut être en tête à la fin du groupe B avec 28 points et en fait ne plus avoir aucun point après le groupe A.
Tout ceci n'invalide en rien la pertinence de votre demande.

**Comment by alupa15** [comment]
okay je comprends, c'est vrai que c'est logique, 
ça marche merci ;)

**Comment by jflamy** [comment]
combiné avec #505

**Comment by jflamy** [comment]
Une fonctionnalité de tableau en temps réel par équipes avec adaptation du pointage pour la fédé française a été faite.
(c'est une extension au module [owlcms-tracker](https://github.com/owlcms/owlcms-tracker?tab=readme-ov-file#owlcms-tracker))
Si vous êtes toujours impliqué et intéressé, répondre à ce commentaire
