### ISSUE TITLE
Automatic publishing of `fop/config` MQTT message

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#692]
**Is your feature request related to a problem? Please describe.**
Integrations that need to know which platforms are available currently need to introduce arbitrary delays before requesting the config or use complex logic to track platforms based on `fop/startup` messages.

**Describe the solution you'd like**
On startup and when a platform is added/edited/updated, a new `fop/config` message is published.

**Describe alternatives you've considered**
Listen to `fop/startup` messages and either track every platform in the startup within a certain timeframe or publish a `config` message after a delay. Currently publishing a `config` message immediately upon receiving a `fop/status` message results in a `fop/config` message that contains stale platform information.

**Comment by scottgonzalez** [comment]
On a related note, there is currently no message published when a platform is removed. This request was address that since the `fop/config` message would be now be triggered in this case and provide the current set of platforms.

**Comment by jflamy** [comment]
Need to write down clearly the minimal change required.
Is publishing fop/startup when a platform is deleted enough (causing interested parties to come back for fop/config) ?

**Comment by scottgonzalez** [comment]
Yes, that should be sufficient for my case.

**Comment by jflamy** [comment]
Turned out to be "simpler" to publish fop/config on startup and on every edit/delete.  No debouncing needed.
see 43.0.0-alpha01
