### ISSUE TITLE
Make elite points classification (Spain)

### ISSUE THREAD

**Issue by danirueda** [jflamy/owlcms4#701]
It would be great for Spanish users to have elite points classification as a column in competition results and as a sheet in sheet results like Sinclair or Robi points for male and female.

## What are elite points (puntos élite)?
Elite points (Puntos Élite) is a score that is only used in Spain. It's used as a qualifying score which an athlete can participate in national championships. It's the same as a qualifying total but with score. Also it's used to make a global classification for all athletes and win cups or medals like Sinclair points in competitions.

### How is it calculated?
This explanation is not exactly, but it's the main procedure.

For each period of time (years) for each category the average of ten world best totals is calculated and elite score is a percentage of this average. For example, let's imagine in M89 this average is 387 kg. If an athlete total is 245 kg his points are (245/387)*100 = 63,30 elite points.

All points for all group ages for all categories for all totals for both genders are calculated and stored in elite points tables. And to know how much points and athlete has done only we have to look the table.

## Where can I find those points?
Elite points tables are stored in [Spanish Weightlifting Federation web page](https://www.fedehalter.org/). They can be found here.

* [Female elite points table](https://www.fedehalter.org/mdocs-posts/tabla-elite-femenina/) - It can be downloaded directly from [this link](https://www.fedehalter.org/mdocs-posts/tabla-elite-femenina/?mdocs-file=5550&mdocs-url=false).
* [Male elite points table](https://www.fedehalter.org/mdocs-posts/tabla-elite-masculina/) - It can be downloaded directly from [this link](https://www.fedehalter.org/mdocs-posts/tabla-elite-masculina/?mdocs-file=5552&mdocs-url=false). 

## How can I scrap information?
You can use:
1. `pdfgrep` to get table rows from PDF with a minimal regex like `[0-9]+.*`.
2. `grep` and  `sed` to clean data.
3. Write a small script in Python or Shell to add all left delimiters because of white cells in source and get a CSV file to use in code.

## What would be the best way to get this clasification?
Because this is only a score used in Spain I think there are two ways.

1. If language es_ES is selected, a new column and news sheet for both genders will appear in results sections and results documents.
2. Put a check in competition options to check and get the column and sheet in results sections and results documents for both genders.
3. A mix of previous options. If language es_ES is selected, a check in competition options will appear and the user can check it.

**Comment by jflamy** [comment]
You can create your own Excel template and do all the computations you
want.  You would simply add the Excel to the local/templates directory.

You would have your tables inside the template file, usually in separate
sheets. Then you would use the Excel bloom up function to use the values in
a formula.
When your tables change you would update the Excel. If this needs to be
dynamic you can use VBA code but such reference tables are usually updated
yearly or less.

To use, would simply select your custom template from the list.

There would be no changes to the program.

Le dim. 9 juill. 2023 à 13:52, Daniel Rueda ***@***.***> a
écrit :

> It would be great for Spanish users to have elite points classification as
> a column in competition results and as a sheet in sheet results like
> Sinclair or Robi points for male and female.
> What are elite points (puntos élite)?
>
> Elite points (Puntos Élite) is a score that is only used in Spain. It's
> used as a qualifying score which an athlete can participate in national
> championships. It's the same as a qualifying total but with score. Also
> it's used to make a global classification for all athletes and win cups or
> medals like Sinclair points in competitions.
> How is it calculated?
>
> This explanation is not exactly, but it's the main procedure.
>
> For each period of time (years) for each category the average of ten world
> best totals is calculated and elite score is a percentage of this average.
> For example, let's imagine in M89 this average is 387 kg. If an athlete
> total is 245 kg his points are (245/387)*100 = 63,30 elite points.
>
> All points for all group ages for all categories for all totals for both
> genders are calculated and stored in elite points tables. And to know how
> much points and athlete has done only we have to look the table.
> Where can I find those points?
>
> Elite points tables are stored in Spanish Weightlifting Federation web
> page <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICBbcjkNNCLH46NvS-2F0ZsmGR5SSmt0KSmBeL73bamddpx3FnG_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh515oCrlwwomVVoGKXDXa4KCGeblEEU6H6zSaB6xhuSH5XBOa-2FDTXkR7AaRDoHram-2BZxWYXfNKkx5Q01uymCVLDNioS0edvJWE4ceZSfgDA4RCt0GnnHpTgJo0r8aNZFSvPAnBuqOSwFyC3O-2BppAiDpNg-3D-3D>. They can be found here.
>
>    - Female elite points table
>    <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICBbcjkNNCLH46NvS-2F0ZsmGRIcaZXQC2Fp-2FBWXYcqqa-2BUcwBRBCZ8jmaRwDGbepg8Jt3QElN7sVKe8Mw5rB74i-2BM-3D_J3t_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh513NU37-2FnNg3QI3P7d7jQrPDUVGjTaF92j2nisPlrQG90yTjJsXo2LS8Wkb4aYNM0ov6NXJf6pZ1MpyErt0nQ1Hb4l-2Bb70NY3t0cZP7-2Ba0CJyQSbeQd2Jte-2FQXuKrlNvkWQFpnqM7gn-2BSvNFD-2FVW2Eyw-3D-3D> - It
>    can be downloaded directly from this link
>    <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICBbcjkNNCLH46NvS-2F0ZsmGRIcaZXQC2Fp-2FBWXYcqqa-2BUcwBRBCZ8jmaRwDGbepg8Ji6TEDdh5oqBLMOJpe6QnLOI43UKv88sy0N5J1D50Nx6Uk4MP-2F5v19P9G8npO5tISA-3D-3De00s_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh51v3n4iGAwwhUpSRqjFSzyP4hpid2UnsdTWmyNhR0oi3fPAYhxs8IjzsQLaPpgimeXR1m88hAjdzO8uIOXSR5jToE9UeSV4Wfg-2Fysu8EL0cQJZxavW-2B1N6bzxZrcdmVRt2zZDUSr2MQeV25pHv5M42dw-3D-3D>
>    .
>    - Male elite points table
>    <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICBbcjkNNCLH46NvS-2F0ZsmGRIcaZXQC2Fp-2FBWXYcqqa-2BUBsEo5v5USDm0ipBsbgYZYwJKpSH2eMyuCMtCM5MKG5A-3D0UuU_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh51MkytdpWiTjEc6K0dLJ4CT3cENbZkentDUW-2BINOMytjHX1hvU0dJZuUNQX8oaJy0nWNZ4AXgedo6Vxno6IvE3hbGXl8O3I6NalaWOPTUfVvFBBHT7BtHePqwpxKi4YceqXPXgYchUOOmU-2BEJ4iSJ-2B-2BA-3D-3D> - It
>    can be downloaded directly from this link
>    <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICBbcjkNNCLH46NvS-2F0ZsmGRIcaZXQC2Fp-2FBWXYcqqa-2BUBsEo5v5USDm0ipBsbgYZY1MGBWQjY7ueXpczqFc80pM9HT3DgjfWfP8F-2FthZyjYi65yvX5FuwytcUzAmy6ZqUw-3D-3DIPp9_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh51r2xbchu9DJTgGzbr-2BOBlHQHomKpf4seT7jRa6StGVPvxplrmqT7a6Vwwjx36xZdxZBJo1FpbX-2Fy1oItzrCkmUwSrLFNwOjnMh5DjJhUKFQ65fqToM1fT703diKLEJXVBM5X9yiBVjT-2BlNJml9SrT7A-3D-3D>
>    .
>
> How can I scrap information?
>
> You can use:
>
>    1. pdfgrep to get table rows from PDF with a minimal regex like
>    [0-9]+.*.
>    2. grep and sed to clean data.
>    3. Write a small script in Python or Shell to add all left delimiters
>    because of white cells in source and get a CSV file to use in code.
>
> What would be the best way to get this clasification?
>
> Because this is only a score used in Spain I think there are two ways.
>
>    1. If language es_ES is selected, a new column and news sheet for both
>    genders will appear in results sections and results documents.
>    2. Put a check in competition options to check and get the column and
>    sheet in results sections and results documents for both genders.
>    3. A mix of previous options. If language es_ES is selected, a check
>    in competition options will appear and the user can check it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICMMwxrmQ5t4YYteB6LEqhedasFyhr-2BiIrutaLljtnRQee1Wg6ZoMJTviO00Y42b9cA-3D-3DySp1_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh51YVsYOim9y8aWeO5tOULv7Nfu9cwr1t0MzpEG9Y2YqwCWvj5GKViAiFGwVSQFX2URYPh4AnFD62iHeSvOAo2FgyRitJMwaBXSiQAEqM9HVhBZVHS4eDZcYWHhVLcnQaf-2FA8JuaiGZqEh7PAPc8z6qcQ-3D-3D>, or unsubscribe
> <https://u31188123.ct.sendgrid.net/ls/click?upn=twvwc57zWERHmKZbfuRICGWiUOjzw-2BuO0cWzQATJEwWt1x36krrFuZOOa7gupKh3fZzerN9KqmdbKk9xj3H0jvpCnvp1YAUXxUgRe5nRKkq5RVJ7p0-2FawhiMST6XtPp1NDHTdldvlceIOJYr8tyYng-3D-3Dvqxp_U31jt5HgHBh7k3Grc5s4l4Dftbug7qATGPHZF2dCsL5z7HRVJYKZhzc-2FYHzO-2BGh3JAU6p-2B4S3z6klpKcFhDLXW6Pl8SNIoSoMcg1oeAt-2BeBpLpvkr8YLYxJ7r8Lprh51q08iISq4cPSmPtnqFQMS3C1YobUA4b3SMHu3XtuMaSNH5CkPVteJcLmaQ-2BwiM9s-2FA7pmQiujtcoxZnOYKBV7bYOzJUy07j2DDoCqJIy8kNdZFEfYtwZ0mQ-2BTz-2FxW-2BlPCu4tjQyCYqXr3RIeYDsqmBA-3D-3D>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
(Envoyé de mon téléphone mobile.)

**Comment by jflamy** [comment]
As explained, what you require can already be done without changing owlcms

**Comment by danirueda** [comment]
I'll do it. When I got it, I'll make a pull request or I'll send you the file.

Thank you!

**Comment by jflamy** [comment]
Many federations have their own set of files that they update
periodically.  For example, national records, or variations on the standard
templates to add logos etc.

You will likely also have regional flags, federation logos, eventually
tweaked style sheets, etc.

So it is better for you to create à Spain « local » with all your additions
or overrides.   That way any Spanish club or region using owlcms would just
drop the folder on top of the existing local and accept replacing existing
files if needed.

> Message ID: ***@***.***>
>
-- 
(Envoyé de mon téléphone mobile.)

**Comment by danirueda** [comment]
I work alone and I would like all regional federations in Spain to have
this functionality. I understand this is a change only for a country and
It's useless to have it globally in software, so I'll contact with all
regional federations and I'll share that Excel template when I got it. Who
knows, perhaps someone has this already or I can be the first to do it!

Thank you!

**Comment by danirueda** [comment]
@jflamy I got it!

It's not 100% automatic, but 90%. As you said I scraped the tables and I put them in two hidden sheets.

After this I removed columns and changed template variable `category` to `bWCategory` to match elite point tables headers and I put the formula in template cell.

When book is generated I have to write category cells again for the formula to be recalculated and finally use bloom up function because formula is referenced to the first row due to template.

For global classification also I have to make sheet order by elite points column descending and it's done.

Here are the results.

Thank you!

# Global classification
## Female
![elite-femenino-total](https://github.com/jflamy/owlcms4/assets/16139263/6f154023-08ad-42f8-9f7f-85e15a2ae3c9)

## Male
![elite-masculino-total](https://github.com/jflamy/owlcms4/assets/16139263/356946d7-b9a5-4b62-9b8f-1af25d1b6dcc)

# Categories
## Female
![elite-femenino](https://github.com/jflamy/owlcms4/assets/16139263/c937233d-8741-417c-9e7d-e8478fbf45f5)

## Male
![elite-masculino](https://github.com/jflamy/owlcms4/assets/16139263/14c43348-718a-439f-a44c-86ffa98fba21)
