### ISSUE TITLE
Personal Record Attempt alert

### ISSUE THREAD

**Issue by dw171no** [jflamy/owlcms4#713]
**Describe the solution you'd like**
The Personal Best info is a useful addition to athlete info, and it is good that it shows up on scoreboards for the current lifter.

We use owlcms for our in house competitions, which aside from being unsanctioned, most of our lifters are beginners who never threaten to break state, national or international records.

But a great feature to celebrate the acheivements of our lifters would be to have the ability to show a "Personal Record Attempt" banner on the scoreboard, in the same place as where the 'Record Attempt' banner shows.

Noting how often a Personal Best will be set (particularly on a third lift), this feature would have to be toggled on as it wouldn't be wise to have it on by default (and would not be appropriate for sanctioned competitions)

A few thoughts on how to implement:
- Add a check box to the Competition Setup / Competition Rules / Non Standard Rules section: "Show personal record attempts alerts"
- Only allow this feature to work if Records files have not been loaded (to ensure functionality does not clash)

**Describe alternatives you've considered**
Announcer can monitor the Personal records on the scoreboard and announce them

**Comment by jflamy** [comment]
There is no alert on a personal record.
They are only shown on the board, when present.
Many sanctioned competitions take place at the city/regional level and showing personal records remains relevant.
