### ISSUE TITLE
Notify TO when athlete is taking a CJ attempt that violates the 20 kg rule

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#717]
If an athlete has decreased the snatch, and needs to increase the CJ, but does not interact with the Marshal, it is possible that the marshal does not notice that the weight requested is illegal.  There should be a warning to all TOs that the weight is illegal.

**Comment by jflamy** [comment]
Was already implemented.


![Image](https://github.com/jflamy/owlcms4/assets/678663/c1e1d9c8-9623-4205-8248-2edb293ef56c)
