### ISSUE TITLE
MQTT: Include Jury Size in Config

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#728]
**Is your feature request related to a problem? Please describe.**
External devices do not know if owlcms is configured for a three member jury or a five member jury. As a result, any external devices for juries must include their own config setting for the jury size, which could potentially not match the actual setting in owlcms.

**Describe the solution you'd like**
Include the jury size in the `fop/config` message and auto-publish the config any time the jury size changes.

**Describe alternatives you've considered**
Independent configuration setting in the external devices, which may be out-of-sync with owlcms.

**Comment by scottgonzalez** [comment]
Looks like this part wasn't implemented:

> auto-publish the config any time the jury size changes.

**Comment by jflamy** [comment]
Fixed. Will be in next release.
