### ISSUE TITLE
Add good lift & bad lift keyboard shortcuts on announcer console

### ISSUE THREAD

**Issue by ClementAdam** [jflamy/owlcms4#749]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use keyboard shortcuts for solo refereing on the announcer console.

**Describe the solution you'd like**
Add the shortcuts key 'g' for good lift and key 'b' for bad lift.

**Describe alternatives you've considered**
Any other keyboard shorcut that leads to enter good or bad lift into the sytem.

**Additional context**
I am setting up a USB Keypad with timekeeping and decision shortcuts for the announcer.

**Comment by jflamy-dev** [comment]
Using alphabetical keys is always a little bit touchy because it would prevent the announcer from typing these characters in a future extension to the announcer page.
I would prefer other characters that are not likely to be typed.  I would propose something like F2 and F4 that are not Chrome shortcuts either (and that have the same keycodes on AZERTY and QWERTY keyboards)

**Comment by ClementAdam** [comment]
Thanks for your answer, any shortcut key would be fine for our needs !Le 30 sept. 2023 à 14:18, jflamy-dev ***@***.***> a écrit :﻿
Using alphabetical keys is always a little bit touchy because it would prevent the announcer from typing these characters in a future extension to the announcer page.
I would prefer other characters that are not likely to be typed.  I would propose something like F2 and F4 that are not Chrome shortcuts either (and that have the same keycodes on AZERTY and QWERTY keyboards)

**Comment by ClementAdam** [comment]
﻿Thanks for your answer, any shortcut key would be fine for our needs !Le 30 sept. 2023 à 14:18, jflamy-dev ***@***.***> a écrit :﻿
Using alphabetical keys is always a little bit touchy because it would prevent the announcer from typing these characters in a future extension to the announcer page.
I would prefer other characters that are not likely to be typed.  I would propose something like F2 and F4 that are not Chrome shortcuts either (and that have the same keycodes on AZERTY and QWERTY keyboards)

**Comment by jflamy** [comment]
will be in 44.1.0
F2 = good, F4 = bad.
