### ISSUE TITLE
Message when calling referees

### ISSUE THREAD

**Issue by ClementAdam** [jflamy/owlcms4#750]
**Describe the bug**
When calling a specific referee, the message in the jury console and on the announcer screen shows that all referees are called.

**owlcms version**
v43.0.6 - French

**To Reproduce**
1. Go to Jury Console
2. Click on Call Referees
3. Click on Call Referee 1, 2 or 3
4. See error : The message shows that all referees are called by the jury.
5. If one referee has already been called, no message is shown if we try to call another referee prior to click on restart the competition (for instance if you need to call referee 1 & 2 only). 

**Expected behavior**
A message saying the specific referees that was meant to be called. A new message could pop-up if we call another referee.

**Screenshots**
![Capture](https://github.com/jflamy/owlcms4/assets/24864632/60dddffc-fd78-4c59-b7f6-1925f89275d1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge 
 - Version 117.0.2045.43

**Additional context**
I am making a USB keypad for the president of the jury and linking every shortcuts of the jury console to it.

**Comment by jflamy-dev** [comment]
The notification label should be simply "Jury Discussion with Referee(s)".  The purpose of the notification is to inform the announcer/timekeeper/marshall that the competition is interrupted.   The jury president himself calls the referees verbally if there are no notification lights/beeps on the jury keypads.   The announcer does *not* call the referees to the jury table -- this is a "private" matter between the jury and the referees.
