### ISSUE TITLE
Registration Category Results is incorrectly production Eligibility Category Results

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#782]
**Describe the bug**
On the Competition Results page, the Registration Category Results and Eligibility Category Results documents are identical (both include all eligible categories). The Registration Category Results should have a unique entry per athlete.

**owlcms version**
version 44.2.0

**To Reproduce**
1. Go to 'Competition Results'
2. Click on 'Registration Category Results'
3. Choose a template (I was using USAWResultsTemplate.xsl).
4. See multiple rows for athletes eligible for multiple categories.

**Expected behavior**
Unique results per athlete, based on registered category.

**Additional context**
The 'Session Results' page with 'All Sessions' selected correctly produces the Registration Category Results document.

**Comment by jflamy** [comment]
Fixed in 42.2.2.
