### ISSUE TITLE
Support lack of 5kg bumper

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#785]
Provide a way to use 2.5kg bumper + 2.5kg plate as substitute for 5kg bumper.
(or 2x2.5kg bumpers)

Ideas:
- a checkbox with "require bumper plate" so the 5kg metal plate is not used alone
- allow again to set a number for the available 2.5kg metal plates. 
- allow again to set a number for the available 2.5kg bumpers.

**Comment by scottgonzalez** [comment]
For us, we don't care if there's a heavier change plate in use, so a 2.5 kg bumper + 5 kg change plate is fine. The main concern is preferring any bumper plate over only change plates (so 2.5 kg + 2.5 kg change vs. only 5 kg change).

**Comment by jflamy** [comment]
fixed in 43.3.0-beta01
