### ISSUE TITLE
Add Q-Points Team Score

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#793]
**Is your feature request related to a problem? Please describe.**
We're testing a Team Score per average of Q-Points.

**Describe the solution you'd like**
Team Results including average Q-Points scored.

Wondering if that would be possible!

**Comment by jflamy** [comment]
Already done in release 44.3 or 44.4. Use QProtocol template. 
Selection of which point system to use on scoreboard is a separate issue.

**Comment by jflamy** [comment]
Sorry I read too quickly. Team score as average. This allows teams of uneven sizes. There is currently no average feature, but this makes sense.  Will take into account in my next batch of changes for point-based formulas.

**Comment by JDFS404** [comment]
Hi @jflamy I don't see the Q-points sheets in the final results package, or am I blind?

**Comment by JDFS404** [comment]
Woops, you're totally right and I am blind :) Merci bien!
