### ISSUE TITLE
Sync problems

### ISSUE THREAD

**Issue by feriattila** [jflamy/owlcms4#813]
**Describe the bug**

version: 45.0.0-beta06

Current Athlete is not in sync with the announcing page

![issue 1 video page ok](https://github.com/jflamy/owlcms4/assets/150864739/d3acda1f-ece7-472c-a651-0bef17e99ae0)
![issue 1 1](https://github.com/jflamy/owlcms4/assets/150864739/31fa6c5b-7ed1-4364-a06d-9fc0241e9475)

**Additional context**

**Comment by jflamy** [comment]
Split the stylesheet problem as a separate problem. #814

**Comment by jflamy** [comment]
Cannot currently reproduce the problem when using multiple browsers.

Note that when running multiple tabs or windows from the same browser, edge and chrome make inactive displays "sleep", so this can lead to strange behavior with multiple windows.  I suggest you use the settings below.  If you can reproduce the problem, please reply with your recipe.

In actual competitions you would not have multiple windows on the same laptop, and if you do, you should use these settings.
Or even better, use two different browsers, with only one tab each (Edge + Chrome + Firefox). You can also setup multiple profiles, one per role, and start one browser per role, this would be equivalent.

![Image](https://github.com/jflamy/owlcms4/assets/678663/5da177c3-17b1-4a39-ad70-83879f338355)
