### ISSUE TITLE
Refree decision sync still not working properly

### ISSUE THREAD

**Issue by feriattila** [jflamy/owlcms4#815]
**Describe the bug**

owlcms version 45.0.0-beta06

The refree decision page still not working properly!

![3 diferent browser! Firefox, Opera, Edge, current athlete display](https://github.com/jflamy/owlcms4/assets/150864739/03bf8858-fb35-4b4a-902e-491f91b7873a)
![3 diferent browser! Firefox, Opera, Edge, current athlete video stream](https://github.com/jflamy/owlcms4/assets/150864739/77971b7b-3d1f-4e3e-aa61-5aa6bd98bb88)
![3 diferent browser! Firefox, Opera, Edge, refree decision - video streaming](https://github.com/jflamy/owlcms4/assets/150864739/df4a0f20-7545-4ccd-9294-cf812d98c5f8)

I use windws 10

**Comment by jflamy** [comment]
Decision page is fixed in beta07, not in beta06.
