### ISSUE TITLE
Feature to test flags

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#829]
It would be handy to have some sort of "show all teams with their uploaded flags"-button.

The idea being that you could easily forget one or two flags during upload, and that would not show up before the actual competition unless you do really thorough testing before.

It would also make it possible to test the on screen appearance of the flags uploaded.

An idea for implementation could be a screen listing all teams and their flags as they would show up on the scoreboard.

**Comment by jflamy** [comment]
The flags are now displayed on the team memnbership page next to each team
