### ISSUE TITLE
Issue with flags and code pages

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#830]
There seems to be a codepage issue with the loading of flags. I had uploaded a svg-file named Ålholm.svg (as we had a participant from Ålholm), but no flag showed up on the screens. 

I suspect it could be due to the danish letters in the file name. I am 100% certain that I did upload that fiel together with the others; the other showing up as expected, but also all had names without danish letters.

Version: 45.05

**Comment by jflamy** [comment]
I suspect that the zip you created did not respect the accents or use UTF-8
When trying to zip this with the Windows utility, a warning is given about the Î as being not supported by their zip.
Modern zips do support UTF-8 correctly,  the following zip was done with 7z on Windows.

![image](https://github.com/jflamy/owlcms4/assets/678663/d458a196-a19a-4296-b48a-423d880f740a)

**Comment by jflamy** [comment]
Same test with Ålholm, with local.zip created using 7z.  Also works locally.

![image](https://github.com/jflamy/owlcms4/assets/678663/897d7087-3e85-49b1-921d-44e9c4385045)
