### ISSUE TITLE
Automatic break was the wrong type

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#831]
A minor issue is that the automatic break between snatch and C&J sometimes came up as breaks before the presentation, and not breaks before C&J as expected.

**owlcms version**
version 4.45.05

**Comment by jflamy** [comment]
I have no idea how to reproduce this, and currently when running in the cloud there is no permanent copy of the logs kept.
If you can reproduce a sequence that does this, please tell me.

The automatic break is normally triggered when the system detects that the snatch is done.
One additional check I could add it that the snatch cannot be done if no lifts have been performed, which would probably fix the problem.

**Comment by AndersBIK99** [comment]
I'll give it at try (finding steps to reproduce)

**Comment by AndersBIK99** [comment]
Steps to reproduce:

Create session with 1 athlete
Start a break with type Break before presentation
Let the break run to the end.
On the Speaker screen press the Break button a select end break.
Start the competition and let the athlete have 3 attempts.
When the automatic break starts the scoreboard shows break before presentation.

Additonal info: When pressing the Break button on the Speaker screen no Type of break is selected.  All four options are empty

**Comment by jflamy** [comment]
So only break to presentation, no break before snatch ?

**Comment by AndersBIK99** [comment]
We did also have a break before snatch during the competition. The automatic break still showed up as break before presentation. The automatic break must by definition always be of the type Break before C&J. So maybe it is just a question of forcing this type when starting the break?

**Comment by jflamy** [comment]
It should work automatically -- in fact the "one-lifter group" is one of the test setups.
Normally you would have as pre-session scenario

1. schedule presentation time.
2. presentation timer ends and red introduction button for announcer
3. announcer closes dialog if needed and proceeds with intro
4. Clicks on red button again to bring back the timer dialog
5. Announcer Starts the 10 minute snatch break
6. Optionally Clicks on Introduction of officials, introduces officials, ends officials.
7. Snatch break never stopped during the intro of officials.
8. Snatch break ends automatically, ready for first athlete.

I am curious when the CJ break comes in, I will try your recipe.

**Comment by jflamy** [comment]
Thank you, bug is reproducible according to recipe.

**Comment by jflamy** [comment]
The break type is correct. The inference of the display name is incorrect because it thinks that the ceremony is going on (you can have ceremonies during the CJ break, although not the introduction of athletes)
