### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by feriattila** [jflamy/owlcms4#846]
I have some of display issue

I run version 46.0.0-beta02.
OS: Windows 11 Home 23H2
Browser Microsoft Edge Version: 121.0.2277.112 (64 bites)

The following displays cannot be loaded:

Start Display/ Warmup Scoreboards/ Public Scoreboards - none are loaded

![Issue version 46 0 0 beta02 Public Scoreboards](https://github.com/jflamy/owlcms4/assets/150864739/6d0f4c79-1e11-45a7-8ab5-de53b600c220)
![Issue version 46 0 0 beta02](https://github.com/jflamy/owlcms4/assets/150864739/e7eec867-97e9-4abc-8aa5-21ad54f84f11)

**Comment by jflamy** [comment]
Able to reproduce.  Error is inside the web library, not failing in my own code.  Trying to figure out what triggers it.

**Comment by jflamy** [comment]
Will be fixed in 46.0.0-beta03
