### ISSUE TITLE
On the results page, sorting by Q-Points is wrong

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#848]
**Describe the bug**
On the results page, when trying to sort by Q-Points, the results are instead sorted by Sinclair.

**owlcms version**
version 46.0.0-SNAPSHOT (current `dev46`)

**To Reproduce**
1. Go to Session Results
2. Click on Qpoints header
3. See results sorted by Sinclair

Note: This is difficult to observe since most of the time the Sinclair and Q-Points orders will be the same.

**Expected behavior**
The "Qpoints" column sorts by Q-Points.

**Additional context**
Partial fix available at https://gist.github.com/scottgonzalez/08cd3f31c737a07461cf1a70897baabd
Not sure when to use `getqPointsRank` vs. `getQPoints`, and the code in the diff is generating null values.

**Comment by jflamy** [comment]
[owlcmsDatabase_2024-02-18_12h18.json](https://github.com/jflamy/owlcms4/files/14323788/owlcmsDatabase_2024-02-18_12h18.json)

Database that demonstrates issue

**Comment by jflamy** [comment]
Workaround is to use the Excel sheets which show the raw qpoint values.
