### ISSUE TITLE
README.md contains untranslated Github variables

### ISSUE THREAD

**Issue by Bravissimo594** [jflamy/owlcms4#853]
**Describe the bug**
The "Licensing and Notes" section of README.md contains untranslated variables, so links to "Releases" and "License" do not work.

**owlcms version**
version 46.0.0-rc02

**To Reproduce**
1. Go to [https://github.com/jflamy/owlcms4#licensing-and-notes](Licensing and Notes)
2. Click on "Releases" or "License"
3. See error

**Expected behavior**
Clicking should take user to Releases or License pages

**Desktop (please complete the following information):**
 - Present in all browsers I tested

**Comment by jflamy** [comment]
Fixed. In addition to the substitution script not having been run, the domain and the path were wrong (like since forever).
