### ISSUE TITLE
structured data for EventForwarder

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#877]
EventForwarder should send structured information about event outcomes.  Currently sends that information within the CSS classes, not as semantic info.

**Comment by jflamy** [comment]
the item `goodBadClassName` now contains one of the 4 strings

- empty
- request
- good
- fail

**Comment by jflamy** [comment]
(alpha01) Clean-up of the JSON information sent to the /update endpoint of publicresults, to support extraction of information for video production

- in the athlete information, the previous field `goodBadClassName` is now `liftStatus`
- in the group information, there are now two fields, `groupName` and `groupInfo`.  `groupName` now contains only the group name. `groupInfo` contains what is shown on the second line of the scoreboard (group description + attempts done, etc.)

**Comment by scottgonzalez** [comment]
`groupName` is providing the correct value initially, but once lifting starts, it switches to the same value as `groupInfo`.
