### ISSUE TITLE
Remove gender from category name

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#886]
### Discussed in https://github.com/jflamy/owlcms4/discussions/885

<div type='discussions-op-text'>

<sup>Originally posted by **endwaa** April  1, 2024</sup>
I have uploaded a `AgeGroups`-sheet with custom category names. In the "Category"-section the gender is displayed between the category name and the weight class. E.g. a category named "SM" with the weight class 81 is displayed as following: "SM M 81". Is it possible to avoid this behaviour?

Also when I download the results a gender suffix is added, like "M" or "F" after the custom category name.</div>

**Comment by jflamy** [comment]
If a "!" is present as the first character of an age group code, then the age group code is presumed to be already gendered and owlcms will not add genders to the categories.

**Comment by endwaa** [comment]
I presume the "!" will not be part of the displayed category name?

**Comment by jflamy** [comment]
Of course not.  It will be a few more days because I am doing a spring cleanup of that area and we have several competitions as well.

**Comment by jflamy** [comment]
Done in 48.0.0-alpha04.
Do not use this release yet, there are other changes that make it fragile.
