### ISSUE TITLE
Incorrect order for start list and weigh-in

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#912]
Incorrect order of athletes for start list, weigh-in document, and weigh-in page. Each one produces a different order, with the start list being the closest to correct (youth are displayed after masters). In the attached database, session F1 contains youth, junior, senior, and masters. M1 contains multiple youth categories and junior.

[owlcmsDatabase_2024-04-26_22h53.json](https://github.com/jflamy/owlcms4/files/15170830/owlcmsDatabase_2024-04-26_22h53.json)

**Comment by jflamy** [comment]
Made sure the registration order comparator was used throughout for the weigh-in documents, and not the display order which can be different (for example, ignore age groups and only use bw).  Fixed the agegroup comparison in the registration order to ignore championship considerations.
