### ISSUE TITLE
Single ref option

### ISSUE THREAD

**Issue by aaronholt1066** [jflamy/owlcms4#915]
**Is your feature request related to a problem? Please describe.**
British Weightlifting have added in a new rule whereby at a tier 3 competition (local club), a single referee may be used, providing they are at BWL Level 3 Referee level.

**Describe the solution you'd like**
Would it be possible to have the functionality where you can set in the ;prepare competition' section, the ability to switch from the default 3 referees to 1 referee required. 

**Describe alternatives you've considered**

**Additional context**

**Comment by JDFS404** [comment]
This to me seems like a perfect solution for things we see in Netherlands as well. @jflamy perhaps wise to have the keypads mapped to 3 +4 (centre ref) so we can use one set of bluetooth buttons for a single-ref comp?
