### ISSUE TITLE
improve quick mode behavior for "no show" athlete

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#938]
in rc18, during weigh-in quick mode, entering no weight and asking for "update and next" causes a loop back to the current athlete

**Comment by jflamy** [comment]
current workaround is to delete the athletes prior to quick mode.

**Comment by jflamy** [comment]
Changed the code such that clearing the session selected for a "no show" goes to the next unweighed athlete.

**Comment by jflamy** [comment]
The program does currently allow 0 for an entered weight (the client side checks with a regex), the message is misleading.
This could be fixed if the natural workaround is to enter 0.
Adding buttons at the bottom is a pain but doable.

**Comment by scottgonzalez** [comment]
After using this flow with removing athletes from the sessions during quick mode entry, I consider this done.
