### ISSUE TITLE
Provide more data for producing a schedule

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#957]
I would like to produce a schedule that lists all age groups and weight classes for each session.

## Proposal
For the start list template, in addition to providing `lifters`, also provide `sessions`. Add a new class that contains rollup information for each age group (AgeGroupInfo) and store a list of AgeGroupInfo instances on the session.

AgeGroupInfo should contain at least the following:
* The age group name and code (could also just be a property that links to an AgeGroup instance).
* The minimum weight class for the age group in the session.
* The maximum weight class for the age group in the session.
* A formatted range of weight classes for the age group in the session.
  * Example: "45-87+"
  * If there is only one weight class, then just the class is used without a range, e.g., "45".
* The number of athletes in the age group.

**Comment by jflamy** [comment]
sessions is already present. This is what checkin page iterates on.

**Comment by jflamy** [comment]
session.ageGroupInfo.athletesByStartNumber
session.ageGroupInfo.athletesByEntryTotal
session.ageGroupInfo.nbAthletes
session.ageGroupInfo.weightClassRange
session.ageGroupInfo.ageGroup
session.ageGroupInfo.ageGroup.gender
