### ISSUE TITLE
Owlcms4 Mobile Refree Device 

### ISSUE THREAD

**Issue by sakettech** [jflamy/owlcms4#975]
To address the issue of running the OwlCM4 software on both mobile referee devices and PCs without requiring internet access, especially in scenarios like tournaments held in outdoor locations where internet connectivity might be unreliable, you can consider the following solutions:

Offline Mode: Implement an offline mode feature in the OwlCM4 software. This mode would allow referees to access all necessary functionalities without requiring an internet connection. Data synchronization can be managed locally and then synced with the main server once internet connectivity is restored.

Local Network Setup: Set up a local network within the tournament venue. This network can be used to connect all referee devices and PCs to a centralized server hosting the OwlCM4 software. This way, even if the venue lacks internet access, referees can still interact with the software and synchronize data within the local network.

Offline Data Storage: Ensure that essential data required for the tournament, such as athlete profiles, competition schedules, and scoring criteria, are stored locally on each device. This way, even if internet connectivity is lost, referees can continue to access and input data without interruption.

Fallback Mechanism: Implement a fallback mechanism within the OwlCM4 software to handle situations where internet connectivity is lost unexpectedly. This mechanism can automatically switch to offline mode and prompt users to reconnect once internet access is restored.

Pre-Tournament Preparation: Encourage tournament organizers to conduct thorough pre-tournament checks to ensure that all devices are properly configured and capable of running the OwlCM4 software without relying on internet connectivity. This includes testing offline functionalities and backup procedures.

By implementing these solutions, you can ensure smooth operation of the OwlCM4 software during tournaments, even in environments where internet access may be limited or unreliable.

**Comment by scottgonzalez** [comment]
The local network setup is already how owlcms works. There is no requirement to have an internet connection unless you are trying to run a livestream or public results.
