### ISSUE TITLE
Mobile Refree Device Without Internet

### ISSUE THREAD

**Issue by sakettech** [jflamy/owlcms4#976]
To enable mobile referee devices to make decisions without internet access and still display the scoreboard, you could implement the following steps:

Offline Decision Making: Develop the OwlCM4 mobile app to allow referees to make decisions offline. This would involve integrating all necessary functionalities for referee decision-making directly into the app, including scoring, timing, penalties, and any other relevant actions.

**Comment by scottgonzalez** [comment]
owlcms does not require an internet connection, even for referee devices. All devices must be on the same network, but access to the internet is not needed.

Even if a mobile app were created (which would be a completely separate project), you would still have the exact same limitation of requiring a local network for the devices to communicate.

See the [Equipment Setup](https://jflamy.github.io/owlcms4/#/EquipmentSetup) documentation for details and diagrams on how to connect the devices. There is even a section at the bottom about when an internet connection is required (streaming and public results).

**Comment by sakettech** [comment]
It seems like you're describing an issue that occurred during a recent tournament using OWCMS4 (Open Water Competition Management System). Specifically, there was a problem with the referee's mobile device where decisions from two individuals were appearing promptly, but the decision from a third person was delayed. Here's how you can troubleshoot and potentially solve this issue:

Steps to Resolve the Delayed Decision Issue in OWCMS4:
Check Network Connectivity:

Ensure that all referees' mobile devices have a stable and strong internet connection. Weak or intermittent connectivity can cause delays in data transmission.
If possible, connect all devices to the same Wi-Fi network to ensure consistency in network performance.
Update Software:

Verify that all mobile devices are running the latest version of the OWCMS4 application. Software updates often include performance improvements and bug fixes.
Check if there are any pending updates for the mobile operating systems as well.
Device Performance:

Ensure that the third referee’s mobile device is not overloaded with other applications running in the background, which might slow down its performance.
Restart the device to clear any potential glitches.

**Comment by jflamy** [comment]
This looks like bot activity.  Closing.
