### ISSUE TITLE
local override zip needs to be reloaded after json import

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#980]
When importing a json file that contains a zip override, it appears that the zip is not correctly restored.
NOTE: observed when the database already had a zip. Was observed when the zip was cleared before import, and without clearing.  Importing without a prior zip is thought to work (to be confirmed)

Workaround: 

1. export the zip from the database
2. import the json
3. re-import the zip

**Comment by scottgonzalez** [comment]
Alternative workaround is to just restart owlcms.

**Comment by jflamy** [comment]
Cannot currently reproduce with 49.0.1.  Further attempts required.
