### ISSUE TITLE
Withdraw athlete during weigh-in

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#992]
Add ability to withdraw an athlete during weigh-in.

**Comment by scottgonzalez** [comment]
We could add a new text field, `withdrawnFromSession` or similar. We'd add a button to the athlete information dialog to withdraw the athlete. Clicking the button would copy the value of their currently assigned session into the new `withdrawnFromSession` field and then clear out the session field. When this value is set, we can display "(withdrawn from session {withdrawnFromSession})" below the session field.

`setGroup()` should clear the `withdrawnFromSession` field.

**Comment by jflamy** [comment]
Currently removing the athlete from their session will perform a correct withdrawal.
So this is low priority.

**Comment by jflamy** [comment]
Not needed anymore.

**Comment by jflamy** [comment]
Not needed anymore.

**Comment by jflamy** [comment]
Not needed anymore
