### ISSUE TITLE
Allow separate medaling system per age group/championship

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#997]
For local meets that only attract a few youth athletes, it would be useful to run the youth scoring on Sinclair or another point system while running juniors and seniors on total.

**Comment by jflamy** [comment]
Also need to think about team scoring.
- if championship is sinclair-based, medals and rankings still make sense
- The team scoring could still be points-based (first sinclair, second sinclair, etc.)
- or, the team scoring could be sum of sinclairs.

Currently, championships are not stored in the database, and not defined in the agegroups file.

**Comment by jflamy** [comment]
Possible implementation - add the notion of a medaling system to an age group?  A championship is a set of age groups with the same medaling system.

- normal medaling systems: Total, or SnCJTot
- e.g. Masters 40-44 age group. Bodyweights 0-999.  Medaling System: SM(H)F.  Championship: MastersAgeGroups
- e.g. U13 kids, Bodyweights 0-999. Medaling system: Huebner Youth Scaled Totals.  Championship: Youth -- could award best lifter to combined U11 U13 U15 if they all used Youth Scaled.
-
