### ISSUE TITLE
athletes with no session should not be considered for medals

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#999]
must currently delete the athlete instead of just assigning no session

**Comment by scottgonzalez** [comment]
Bumped to L1 based on preferring removing no show athletes vs. deleting athletes.

**Comment by jflamy** [comment]
Missing a category in the medals report; one athlete was removed from session. So the category should be considered complete.

[medalsBugDatabase_2024-07-16_15h41.json](https://github.com/user-attachments/files/16289896/medalsBugDatabase_2024-07-16_15h41.json)



[Masters_W6-SUNDAY_2024-07-14_13h17_00.xlsx](https://github.com/user-attachments/files/16289908/Masters_W6-SUNDAY_2024-07-14_13h17_00.xlsx)


[Medals_W6-SUNDAY_2024-07-14_13h40_09.xlsx](https://github.com/user-attachments/files/16289910/Medals_W6-SUNDAY_2024-07-14_13h40_09.xlsx)

**Comment by jflamy** [comment]
branch 50_medalsWithNoShow has prospective fix.  Ignores unweighed athletes from the group for which medals are being computed (which presumably is finishing lifting or has finished lifting)
